// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Bradley Brown

// GeneratedCalculatorAttributeSource.cs
//
// Source text for the [GeneratedCalculator] attribute, injected into every
// compilation that references the source generator via
// IIncrementalGenerator.RegisterPostInitializationOutput. Lives as a string
// here rather than as a normal C# file in the analyzer because the consumer
// project doesn't reference the analyzer assembly at runtime — only its
// source-generation output participates in the compile.

namespace FracturingFog.CalculatorGen.SourceGen;

internal static class GeneratedCalculatorAttributeSource
{
    public const string HintName = "GeneratedCalculatorAttribute.g.cs";

    public const string FullyQualifiedName =
        "FracturingFog.CalculatorGen.GeneratedCalculatorAttribute";

    public const string Source = """
// <auto-generated/>
#nullable enable
namespace FracturingFog.CalculatorGen
{
    /// <summary>
    /// Assembly-level marker — each instance drives one CalculatorGen
    /// emission at compile time. Replaces the legacy
    /// <c>dotnet run -p CalculatorGen --equation … --name …</c> step.
    /// Multiple attributes per assembly are allowed (one per calculator).
    /// </summary>
    /// <example>
    /// <code>
    /// [assembly: GeneratedCalculator("z*z + c", Name = "MandelbrotZ2", IncludeSelfTest = true)]
    /// </code>
    /// </example>
    [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = true, Inherited = false)]
    [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1019", Justification = "Attribute drives source generation.")]
    internal sealed class GeneratedCalculatorAttribute : global::System.Attribute
    {
        public GeneratedCalculatorAttribute(string equation, string name)
        {
            Equation = equation;
            Name = name;
        }

        /// <summary>Right-hand side of <c>z_{n+1} = …</c>. Required.</summary>
        public string Equation { get; }

        /// <summary>
        /// Generated class name. Suffix <c>Calculator</c> is appended if
        /// missing. Lives in <c>FracturingFog.Calculators.Generated</c>.
        /// </summary>
        public string Name { get; }

        /// <summary>Bailout radius squared. Default 512.0.</summary>
        public double Bailout { get; set; } = 512.0;

        /// <summary>
        /// When true, also emit the companion <c>{Name}SelfTest</c> class
        /// that validates scalar↔AVX2 parity.
        /// </summary>
        public bool IncludeSelfTest { get; set; } = false;
    }
}
""";
}
