// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Bradley Brown

// KleinianCalculator.cs
//
// Kleinian limit set — 3D fractal generated by iterated inversion in a set of
// reflection spheres (a Schottky-style Kleinian group). The limit set of the
// group is the closure of the orbit of any point under group composition;
// rendering it as a 3D solid uses distance-estimated sphere tracing.
//
// First cut ships a fixed tetrahedral 4-sphere preset: spheres of radius √2
// centred at the four even-parity ±1 corners (±1, ±1, ±1) so any pair is
// mutually tangent at their joining-edge midpoint. The origin sits inside all
// four spheres simultaneously — repeated inversion drives a sample point
// toward the limit set on the sphere intersection boundary.
//
// Distance estimator (after Knighty / Fragmentarium pseudo-Kleinian):
//   scale := 1
//   for i in 0 .. iter:
//     pick the sphere whose interior most contains p
//     if p is outside every sphere: break
//     invert p through that sphere; scale *= r² / |p − c|²
//   DE := signed-nearest-sphere distance / scale
//
// The inversion-scale product is the standard chain-rule derivative magnitude
// for sphere inversion: d(p')/dp = (r² / |p − c|²) · (I − 2·(p − c)(p − c)ᵀ
// / |p − c|²). Tracking the scalar prefactor is enough for sphere tracing —
// the orthogonal Householder factor has unit magnitude.

using System;
using System.Threading;
using System.Threading.Tasks;

using FracturingFog.Calculators.Gpu;
using FracturingFog.Interefaces;
using FracturingFog.Rendering;
using FracturingFog.Rendering.Lighting;
using FracturingFog.Models;

namespace FracturingFog;

public sealed class KleinianCalculator : IFractalCalculator
{
    public int Width { get; private set; }
    public int Height { get; private set; }
    public uint[] ColorBuffer { get; private set; } = Array.Empty<uint>();

    // P7b — lazily-constructed GPU calculator. See MandelbulbCalculator for contract.
    private KleinianGpuCalculator? _gpu;

    /// <summary>P2 — low-res interactive preview. See Mandelbulb for contract.</summary>
    public bool LowResPreview { get; set; } = false;

    public double CenterX { get; set; } = 0.0;
    public double CenterY { get; set; } = 0.0;
    public double Zoom { get; set; } = 1.0;
    public int MaxIterations { get; set; } = 96;

    public QualityPreset Quality { get; set; } = QualityPreset.Standard;
    public IColorMap ColorMap { get; set; } = new HsvPalette();

    public bool SupportsZoomPan => true;

    public FractalParameters FractalParameters { get; set; } = new();

    public KleinianCalculator(int width, int height) => Resize(width, height);

    public void Resize(int width, int height)
    {
        Width = width;
        Height = height;
        ColorBuffer = new uint[width * height];
    }

    public void Calculate(CancellationToken ct = default)
    {
        ColorMap.MaxIterations = 256;
        int fullW = Width;
        int fullH = Height;
        bool lowRes = LowResPreview;
        double lrScale = lowRes ? Math.Clamp(FractalParameters.LowResPreviewScale, 0.25, 1.0) : 1.0;
        var dims = FracturingFog.Rendering.LowResPreview.ComputeDims(fullW, fullH, lrScale);
        int width = dims.Width;
        int height = dims.Height;
        uint[] renderBuffer = lowRes ? new uint[width * height] : ColorBuffer;

        int deIter   = Math.Max(2, FractalParameters.KleinianIterations);
        int maxSteps = Math.Max(16, FractalParameters.KleinianMaxSteps);
        double eps   = Math.Max(1e-5, FractalParameters.KleinianEpsilon);
        double scaleK = Math.Max(0.25, FractalParameters.KleinianSphereScale);

        // Tetrahedral 4-sphere centres scaled by KleinianSphereScale so the
        // limit set can be "loosened" — at scale 1 the spheres overlap at the
        // origin and the limit set is the cocoon between them; at smaller
        // scales the spheres separate and the limit set splits into discrete
        // shells.
        double r = Math.Sqrt(2.0) * scaleK;     // tangent radius at scale 1
        double[] cx = { +1 * scaleK, +1 * scaleK, -1 * scaleK, -1 * scaleK };
        double[] cy = { +1 * scaleK, -1 * scaleK, +1 * scaleK, -1 * scaleK };
        double[] cz = { +1 * scaleK, -1 * scaleK, -1 * scaleK, +1 * scaleK };

        double setRadius = scaleK * Math.Sqrt(3.0) + r;
        double camDistFloor = setRadius + 0.5;
        double rawCamDist = FractalParameters.KleinianCameraDistance / Math.Max(0.05, Zoom);
        double camDist = Math.Max(camDistFloor, rawCamDist);
        double camTheta = FractalParameters.KleinianCameraTheta;
        double camPhi   = FractalParameters.KleinianCameraPhi;

        double camPX = camDist * Math.Sin(camPhi) * Math.Cos(camTheta);
        double camPY = camDist * Math.Cos(camPhi);
        double camPZ = camDist * Math.Sin(camPhi) * Math.Sin(camTheta);

        double[] fwd = Normalize3(-camPX, -camPY, -camPZ);
        double[] worldUp = { 0, 1, 0 };
        double[] right = Normalize3(
            fwd[1] * worldUp[2] - fwd[2] * worldUp[1],
            fwd[2] * worldUp[0] - fwd[0] * worldUp[2],
            fwd[0] * worldUp[1] - fwd[1] * worldUp[0]);
        double[] up = {
            right[1] * fwd[2] - right[2] * fwd[1],
            right[2] * fwd[0] - right[0] * fwd[2],
            right[0] * fwd[1] - right[1] * fwd[0],
        };

        // Phase 20b — true per-eye camera offset along the right basis.
        double eyeOffset = FractalParameters.Lighting.StereoEyeOffset;
        if (eyeOffset != 0)
        {
            camPX += right[0] * eyeOffset;
            camPY += right[1] * eyeOffset;
            camPZ += right[2] * eyeOffset;
        }

        double aspect = (double)width / height;
        double fovBase = Math.Tan(0.5 * Math.PI / 3.0);
        double zoomLensFactor = rawCamDist >= camDistFloor
            ? 1.0
            : Math.Max(0.05, rawCamDist / camDistFloor);
        double fovScale = fovBase * zoomLensFactor;

        double panU = CenterX;
        double panV = -CenterY;

        double[] light = Normalize3(
            Math.Sin(FractalParameters.KleinianLightPhi) * Math.Cos(FractalParameters.KleinianLightTheta),
            Math.Cos(FractalParameters.KleinianLightPhi),
            Math.Sin(FractalParameters.KleinianLightPhi) * Math.Sin(FractalParameters.KleinianLightTheta));

        // Phase 1c — Lighting struct is authoritative for Light1/2/3.
        var fx = FractalParameters.Lighting;
        var deStruct = new De(cx, cy, cz, r, deIter);

        // Hoisted for shared use by GPU dispatch + CPU path.
        double sceneRadius = camDist + setRadius * 2.0 + 4.0;

        // P7b — opt-in GPU raymarch path (cheap-palette shading). Fixed
        // 4-sphere preset matches the CPU centres array. See
        // MandelbulbCalculator for the FX-drop trade-off + P7c lift plan.
        if (fx.UseGpuRender && !lowRes)
        {
            var rp = new GpuRaymarchParams
            {
                Width = width, Height = height,
                CamX = camPX, CamY = camPY, CamZ = camPZ,
                TargetX = 0, TargetY = 0, TargetZ = 0,
                FwdX = fwd[0], FwdY = fwd[1], FwdZ = fwd[2],
                RightX = right[0], RightY = right[1], RightZ = right[2],
                UpX = up[0], UpY = up[1], UpZ = up[2],
                FovScale = fovScale, Aspect = aspect,
                PanU = panU, PanV = panV,
                LightX = light[0], LightY = light[1], LightZ = light[2],
                MaxSteps = maxSteps, Eps = eps,
                CullRadiusSq = 0.0,
                InSetColor = ColorMap.InSetColor,
            };
            var kp = new KleinianGpuParams
            {
                C0X = cx[0], C0Y = cy[0], C0Z = cz[0],
                C1X = cx[1], C1Y = cy[1], C1Z = cz[1],
                C2X = cx[2], C2Y = cy[2], C2Z = cz[2],
                C3X = cx[3], C3Y = cy[3], C3Z = cz[3],
                Radius = r,
                DEIter = deIter,
                SceneRadius = sceneRadius,
            };
            var sp = GpuShadingParams.Build(in fx);
            _gpu ??= new KleinianGpuCalculator();
            if (_gpu.Render(renderBuffer, rp, sp, kp))
            {
                // #84 — GPU raymarch skips the CPU post stack; draw the debug
                // HUD directly so the light compass still appears on GPU frames.
                ScreenSpacePost.ApplyDebugHud(renderBuffer, width, height, in fx);
                return;
            }
        }

        // Phase 4 — G-buffer for SSAO post-pass.
        float[]? depthBuf = null;
        float[]? normalBuf = null;
        if (fx.SsaoSamples > 0)
        {
            depthBuf = new float[width * height];
            normalBuf = new float[3 * width * height];
            ScreenSpacePost.ClearGBuffer(depthBuf, normalBuf);
        }
        // Phase 7 — HDR buffer for tonemap/bloom.
        float[]? hdrBuf = null;
        bool wantPost = fx.ToneMap != ToneMapOperator.None || fx.BloomStrength > 0;
        if (wantPost)
        {
            hdrBuf = new float[3 * width * height];
            ScreenSpacePost.ClearHdrBuffer(hdrBuf);
        }

        Parallel.For(0, height, new ParallelOptions { CancellationToken = ct }, y =>
        {
            if (ct.IsCancellationRequested) return;
            double v = (1.0 - 2.0 * (y + 0.5) / height) * fovScale + panV;
            int rowBase = y * width;
            for (int x = 0; x < width; x++)
            {
                double u = (2.0 * (x + 0.5) / width - 1.0) * fovScale * aspect + panU;
                double rdx = right[0] * u + up[0] * v + fwd[0];
                double rdy = right[1] * u + up[1] * v + fwd[1];
                double rdz = right[2] * u + up[2] * v + fwd[2];
                var dn = Normalize3(rdx, rdy, rdz);
                rdx = dn[0]; rdy = dn[1]; rdz = dn[2];

                double px = camPX, py = camPY, pz = camPZ;
                double tTotal = 0;
                bool hit = false;
                int hitStep = 0;

                for (int step = 0; step < maxSteps; step++)
                {
                    double dist = KleinianDE(px, py, pz, cx, cy, cz, r, deIter);
                    if (dist < eps) { hit = true; hitStep = step; break; }
                    if (tTotal > sceneRadius) break;
                    px += rdx * dist; py += rdy * dist; pz += rdz * dist;
                    tTotal += dist;
                }

                int idx = rowBase + x;
                if (!hit)
                {
                    // Ray-miss → sky backdrop when toggle on; InSetColor off (see MandelbulbCalculator).
                    renderBuffer[idx] = fx.ShowSkyBackdrop
                        ? ShadingPipeline.SkyColorHdri(rdx, rdy, rdz, in fx)
                        : ColorMap.InSetColor;
                    continue;
                }

                double h = eps * 2;
                double n0 = KleinianDE(px + h, py, pz, cx, cy, cz, r, deIter)
                          - KleinianDE(px - h, py, pz, cx, cy, cz, r, deIter);
                double n1 = KleinianDE(px, py + h, pz, cx, cy, cz, r, deIter)
                          - KleinianDE(px, py - h, pz, cx, cy, cz, r, deIter);
                double n2 = KleinianDE(px, py, pz + h, cx, cy, cz, r, deIter)
                          - KleinianDE(px, py, pz - h, cx, cy, cz, r, deIter);
                var nrm = Normalize3(n0, n1, n2);

                float smooth = (float)hitStep * (192f / Math.Max(1, maxSteps))
                             + (float)(tTotal * 0.5);
                uint baseColor = (uint)ColorMap.Map(smooth, 0f, 256, (float)nrm[0], (float)nrm[1]);

                // Phase 2 — shading via shared pipeline.
                var inputs = new ShadingInputs(
                    px, py, pz, nrm[0], nrm[1], nrm[2],
                    rdx, rdy, rdz, tTotal, 0.0, hitStep, eps);
                renderBuffer[idx] = ShadingPipeline.Shade<De>(
                    in inputs, baseColor, in fx, in deStruct, true,
                    idx, depthBuf, normalBuf, hdrBuf);
            }
        });

        ScreenSpacePost.BeginGpuFrame(renderBuffer, width, height, in fx);
        if (depthBuf is not null && normalBuf is not null)
            ScreenSpacePost.ApplySsao(renderBuffer, depthBuf, normalBuf, width, height, in fx);
        if (hdrBuf is not null && depthBuf is not null)
            ScreenSpacePost.ApplyHdrDof(hdrBuf, depthBuf, width, height, in fx);
        if (hdrBuf is not null)
            ScreenSpacePost.ApplyToneMapBloom(renderBuffer, hdrBuf, width, height, in fx);
        if (depthBuf is not null && normalBuf is not null)
            ScreenSpacePost.ApplyEdgeInk(renderBuffer, depthBuf, normalBuf, width, height, in fx);
        ScreenSpacePost.EndGpuFrame(in fx);

        if (lowRes)
            FracturingFog.Rendering.LowResPreview.UpscaleNearest(
                renderBuffer, width, height, ColorBuffer, fullW, fullH);

        // #84 — light-direction compass / param bars / scene clock. Standalone
        // final pass on the composited full-res buffer so it survives both the
        // low-res upscale and the GPU-raymarch early-out. Self-guards on flags.
        ScreenSpacePost.ApplyDebugHud(ColorBuffer, fullW, fullH, in fx);
    }

    /// <summary>
    /// Sphere-inversion distance estimator. Iterate "invert through deepest
    /// containing sphere" until the sample point falls outside every sphere,
    /// tracking the scalar inversion-scale product as the chain-rule
    /// derivative magnitude. DE = signed nearest-sphere distance / accumulated
    /// scale.
    /// </summary>
    /// <summary>P3 — concrete DE struct. Holds references to the sphere
    /// centre arrays + tangent radius; iter loop runs inside KleinianDE.</summary>
    public readonly struct De : FracturingFog.Rendering.Lighting.IDistanceEstimator
    {
        private readonly double[] _cx, _cy, _cz;
        private readonly double _r;
        private readonly int _iter;
        public De(double[] cx, double[] cy, double[] cz, double r, int iter)
        { _cx = cx; _cy = cy; _cz = cz; _r = r; _iter = iter; }
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public double Evaluate(double x, double y, double z)
            => KleinianDE(x, y, z, _cx, _cy, _cz, _r, _iter);
    }

    private static double KleinianDE(
        double px, double py, double pz,
        double[] cx, double[] cy, double[] cz, double r,
        int iter)
    {
        double r2 = r * r;
        double scale = 1.0;
        int n = cx.Length;

        for (int i = 0; i < iter; i++)
        {
            // Find sphere whose interior most-contains p (largest negative
            // signed distance). If every signed distance is non-negative, p is
            // outside all spheres → escape.
            int bestK = -1;
            double bestDeep = 0.0;          // most-negative signed distance
            for (int k = 0; k < n; k++)
            {
                double dx = px - cx[k];
                double dy = py - cy[k];
                double dz = pz - cz[k];
                double d = Math.Sqrt(dx * dx + dy * dy + dz * dz) - r;
                if (d < bestDeep) { bestDeep = d; bestK = k; }
            }
            if (bestK < 0) break;

            double ex = px - cx[bestK];
            double ey = py - cy[bestK];
            double ez = pz - cz[bestK];
            double e2 = ex * ex + ey * ey + ez * ez;
            if (e2 < 1e-30) break;
            double f = r2 / e2;
            scale *= f;
            px = cx[bestK] + ex * f;
            py = cy[bestK] + ey * f;
            pz = cz[bestK] + ez * f;
        }

        // After escape, return distance to the nearest sphere boundary in
        // post-iteration space, scaled back to world space by the accumulated
        // inversion derivative.
        double nearest = double.PositiveInfinity;
        for (int k = 0; k < n; k++)
        {
            double dx = px - cx[k];
            double dy = py - cy[k];
            double dz = pz - cz[k];
            double d = Math.Sqrt(dx * dx + dy * dy + dz * dz) - r;
            double a = Math.Abs(d);
            if (a < nearest) nearest = a;
        }
        if (scale < 1e-30) return 0.0;
        return nearest / scale;
    }

    private static double[] Normalize3(double x, double y, double z)
    {
        double len = Math.Sqrt(x * x + y * y + z * z);
        if (len < 1e-10) return new[] { 0.0, 0.0, 0.0 };
        return new[] { x / len, y / len, z / len };
    }
}
