// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Bradley Brown

// KleinianCalculator.cs
//
// Kleinian limit set — 3D fractal generated by iterated inversion in a set of
// reflection spheres (a Schottky-style Kleinian group). The limit set of the
// group is the closure of the orbit of any point under group composition;
// rendering it as a 3D solid uses distance-estimated sphere tracing.
//
// First cut ships a fixed tetrahedral 4-sphere preset: spheres of radius √2
// centred at the four even-parity ±1 corners (±1, ±1, ±1) so any pair is
// mutually tangent at their joining-edge midpoint. The origin sits inside all
// four spheres simultaneously — repeated inversion drives a sample point
// toward the limit set on the sphere intersection boundary.
//
// Distance estimator (after Knighty / Fragmentarium pseudo-Kleinian):
//   scale := 1
//   for i in 0 .. iter:
//     pick the sphere whose interior most contains p
//     if p is outside every sphere: break
//     invert p through that sphere; scale *= r² / |p − c|²
//   DE := signed-nearest-sphere distance / scale
//
// The inversion-scale product is the standard chain-rule derivative magnitude
// for sphere inversion: d(p')/dp = (r² / |p − c|²) · (I − 2·(p − c)(p − c)ᵀ
// / |p − c|²). Tracking the scalar prefactor is enough for sphere tracing —
// the orthogonal Householder factor has unit magnitude.

using System;
using System.Threading;
using System.Threading.Tasks;

using FracturingFog.Calculators.Gpu;
using FracturingFog.Interefaces;
using FracturingFog.Rendering;
using FracturingFog.Rendering.Lighting;
using FracturingFog.Models;

namespace FracturingFog;

public sealed class KleinianCalculator : IFractalCalculator
{
    public int Width { get; private set; }
    public int Height { get; private set; }
    public uint[] ColorBuffer { get; private set; } = Array.Empty<uint>();

    // P7b — lazily-constructed GPU calculator. See MandelbulbCalculator for contract.
    private KleinianGpuCalculator? _gpu;

    /// <summary>P2 — low-res interactive preview. See Mandelbulb for contract.</summary>
    public bool LowResPreview { get; set; } = false;

    public double CenterX { get; set; } = 0.0;
    public double CenterY { get; set; } = 0.0;
    public double Zoom { get; set; } = 1.0;
    public int MaxIterations { get; set; } = 96;

    public QualityPreset Quality { get; set; } = QualityPreset.Standard;
    public IColorMap ColorMap { get; set; } = new HsvPalette();

    public bool SupportsZoomPan => true;

    public FractalParameters FractalParameters { get; set; } = new();

    public KleinianCalculator(int width, int height) => Resize(width, height);

    public void Resize(int width, int height)
    {
        Width = width;
        Height = height;
        ColorBuffer = new uint[width * height];
    }

    public void Calculate(CancellationToken ct = default)
    {
        ColorMap.MaxIterations = 256;
        int fullW = Width;
        int fullH = Height;
        bool lowRes = LowResPreview;
        double lrScale = lowRes ? Math.Clamp(FractalParameters.LowResPreviewScale, 0.25, 1.0) : 1.0;
        var dims = FracturingFog.Rendering.LowResPreview.ComputeDims(fullW, fullH, lrScale);
        int width = dims.Width;
        int height = dims.Height;
        uint[] renderBuffer = lowRes ? new uint[width * height] : ColorBuffer;

        int deIter   = Math.Max(2, FractalParameters.KleinianIterations);
        int maxSteps = Math.Max(16, FractalParameters.KleinianMaxSteps);
        double eps   = Math.Max(1e-5, FractalParameters.KleinianEpsilon);
        double scaleK = Math.Max(0.25, FractalParameters.KleinianSphereScale);

        // #874 (S1) — the group is now data. The tetrahedral factory reproduces
        // the previously hard-coded 4-sphere centres byte-for-byte (Tier 0), so
        // the DE loops over `gens` instead of a fixed array; future slices vary
        // the group (presets, user spheres, Möbius generators) without touching
        // the render/shade stack. At scale 1 the four spheres overlap at the
        // origin (limit set = the cocoon between them); smaller scales separate
        // them into discrete shells.
        // #875 (S2) — the preset selects the Schottky sphere configuration.
        // #876 (S3) — Custom builds the group from the user-authored sphere list
        // (absolute coordinates, not scaled by KleinianSphereScale); an empty list
        // falls back to the tetrahedral group.
        var group = FractalParameters.KleinianPreset == KleinianPreset.Custom
            ? KleinianGroup.FromSpheres(FractalParameters.KleinianCustomSpheres, deIter)
            : KleinianGroup.FromPreset(
                FractalParameters.KleinianPreset, scaleK,
                FractalParameters.KleinianNecklaceCount, deIter);
        // #877 (S4) — optional rotation fold twists the limit set (pseudo-Kleinian
        // "rotated" construction). Angle 0 → KleinianRotation.None → byte-identical.
        group = group.WithRotation(new KleinianRotation(
            FractalParameters.KleinianRotationAngle * (Math.PI / 180.0),
            FractalParameters.KleinianRotationAxisX,
            FractalParameters.KleinianRotationAxisY,
            FractalParameters.KleinianRotationAxisZ));
        KleinianGenerator[] gens = group.ToArray();
        KleinianRotation rot = group.Rotation;
        var colorSrc = FractalParameters.KleinianColorSource;   // #878
        double deFactor = Math.Clamp(FractalParameters.KleinianDeFactor, 0.1, 1.0);   // #881
        double r = Math.Sqrt(2.0) * scaleK;     // tangent radius (camera framing)

        double setRadius = scaleK * Math.Sqrt(3.0) + r;
        double camDistFloor = setRadius + 0.5;
        double rawCamDist = FractalParameters.KleinianCameraDistance / Math.Max(0.05, Zoom);
        double camDist = Math.Max(camDistFloor, rawCamDist);
        double camTheta = FractalParameters.KleinianCameraTheta;
        double camPhi   = FractalParameters.KleinianCameraPhi;

        double camPX = camDist * Math.Sin(camPhi) * Math.Cos(camTheta);
        double camPY = camDist * Math.Cos(camPhi);
        double camPZ = camDist * Math.Sin(camPhi) * Math.Sin(camTheta);

        double[] fwd = Normalize3(-camPX, -camPY, -camPZ);
        double[] worldUp = { 0, 1, 0 };
        double[] right = Normalize3(
            fwd[1] * worldUp[2] - fwd[2] * worldUp[1],
            fwd[2] * worldUp[0] - fwd[0] * worldUp[2],
            fwd[0] * worldUp[1] - fwd[1] * worldUp[0]);
        double[] up = {
            right[1] * fwd[2] - right[2] * fwd[1],
            right[2] * fwd[0] - right[0] * fwd[2],
            right[0] * fwd[1] - right[1] * fwd[0],
        };

        // Phase 20b — true per-eye camera offset along the right basis.
        double eyeOffset = FractalParameters.Lighting.StereoEyeOffset;
        if (eyeOffset != 0)
        {
            camPX += right[0] * eyeOffset;
            camPY += right[1] * eyeOffset;
            camPZ += right[2] * eyeOffset;
        }

        double aspect = (double)width / height;
        double fovBase = Math.Tan(0.5 * Math.PI / 3.0);
        double zoomLensFactor = rawCamDist >= camDistFloor
            ? 1.0
            : Math.Max(0.05, rawCamDist / camDistFloor);
        double fovScale = fovBase * zoomLensFactor;

        double panU = CenterX;
        double panV = -CenterY;

        double[] light = Normalize3(
            Math.Sin(FractalParameters.KleinianLightPhi) * Math.Cos(FractalParameters.KleinianLightTheta),
            Math.Cos(FractalParameters.KleinianLightPhi),
            Math.Sin(FractalParameters.KleinianLightPhi) * Math.Sin(FractalParameters.KleinianLightTheta));

        // Phase 1c — Lighting struct is authoritative for Light1/2/3.
        var fx = FractalParameters.Lighting;
        // Vol-color slice D (#180) — bake the active theme gradient for the
        // volumetric palette remap (no-op unless VolumePaletteStrength > 0).
        VolumePaletteBaker.Bake(ref fx, ColorMap);
        var deStruct = new De(gens, deIter, rot);

        // Hoisted for shared use by GPU dispatch + CPU path.
        double sceneRadius = camDist + setRadius * 2.0 + 4.0;

        // P7b — opt-in GPU raymarch path (cheap-palette shading). Fixed
        // 4-sphere preset matches the CPU centres array. See
        // MandelbulbCalculator for the FX-drop trade-off + P7c lift plan.
        // #320 — force CPU while an AOV view is active (GPU has no view path).
        // S8 (#404/#487) — this kernel now resolves point/spot lights on the GPU
        // (GpuKernelUtils.ResolveLight); the !HasPositionalLight gate is lifted.
        // #492 added a per-light area-capped shadow hardness (sp.ShadowK1/2/3),
        // so area lights also render on the GPU now (punctual = byte-identical).
        // #874 (S1) — the GPU kernel passes exactly four centres + one radius, so
        // it only serves the uniform 4-sphere inversion group (the tetrahedral
        // preset). Any other group (>4 spheres, mixed radii, non-inversion
        // generators) falls to the general CPU descent below.
        bool gpuEligible = group.AllInversions && group.UniformRadius && gens.Length == 4
                           && !group.HasRotation                              // #877 — rotation fold is CPU-only
                           && colorSrc == KleinianColorSource.Smooth           // #878 — word colouring is CPU-only
                           && deFactor == 1.0;                                 // #881 — under-relaxed stepping is CPU-only
        if (fx.UseGpuRender && fx.DebugAov == AovView.Beauty && !lowRes && gpuEligible)
        {
            var rp = new GpuRaymarchParams
            {
                Width = width, Height = height,
                CamX = camPX, CamY = camPY, CamZ = camPZ,
                TargetX = 0, TargetY = 0, TargetZ = 0,
                FwdX = fwd[0], FwdY = fwd[1], FwdZ = fwd[2],
                RightX = right[0], RightY = right[1], RightZ = right[2],
                UpX = up[0], UpY = up[1], UpZ = up[2],
                FovScale = fovScale, Aspect = aspect,
                PanU = panU, PanV = panV,
                LightX = light[0], LightY = light[1], LightZ = light[2],
                MaxSteps = maxSteps, Eps = eps,
                CullRadiusSq = 0.0,
                InSetColor = ColorMap.InSetColor,
                // S3 (#567) — thin-lens DOF on the GPU kernel. Inactive (aperture 0 /
                // one sample) -> the single centre ray -> byte-identical. Focus auto-
                // resolves to the camera distance when unset.
                DofAperture = ThinLensDof.IsActive(in fx) ? fx.DofAperture : 0.0,
                DofFocus = ThinLensDof.FocusDistance(in fx, camDist),
                DofSamples = ThinLensDof.SampleCount(in fx),
            };
            var kp = new KleinianGpuParams
            {
                C0X = gens[0].Cx, C0Y = gens[0].Cy, C0Z = gens[0].Cz,
                C1X = gens[1].Cx, C1Y = gens[1].Cy, C1Z = gens[1].Cz,
                C2X = gens[2].Cx, C2Y = gens[2].Cy, C2Z = gens[2].Cz,
                C3X = gens[3].Cx, C3Y = gens[3].Cy, C3Z = gens[3].Cz,
                Radius = group.SphereRadius,
                DEIter = deIter,
                SceneRadius = sceneRadius,
            };
            var sp = GpuShadingParams.Build(in fx);
            _gpu ??= new KleinianGpuCalculator();
            if (_gpu.Render(renderBuffer, rp, sp, kp, fx.VolumePalette))
            {
                // #84 — GPU raymarch skips the CPU post stack; draw the debug
                // HUD directly so the light compass still appears on GPU frames.
                ScreenSpacePost.ApplyDebugHud(renderBuffer, width, height, in fx);
                return;
            }
        }

        // Phase 4 — G-buffer for SSAO post-pass.
        float[]? depthBuf = null;
        float[]? normalBuf = null;
        if (fx.SsaoSamples > 0)
        {
            depthBuf = new float[width * height];
            normalBuf = new float[3 * width * height];
            ScreenSpacePost.ClearGBuffer(depthBuf, normalBuf);
        }
        // Phase 7 — HDR buffer for tonemap/bloom.
        float[]? hdrBuf = null;
        bool wantPost = fx.ToneMap != ToneMapOperator.None || fx.BloomStrength > 0;
        if (wantPost)
        {
            hdrBuf = new float[3 * width * height];
            ScreenSpacePost.ClearHdrBuffer(hdrBuf);
        }

        // S3 (#389/#567) — physically-based thin-lens DoF (shared accumulator).
        // Off / aperture 0 → the single-ray path below, untouched (byte-identical).
        bool thinLensDof = ThinLensDof.IsActive(in fx);
        int dofN = ThinLensDof.SampleCount(in fx);
        double dofFocus = ThinLensDof.FocusDistance(in fx, camDist);
        double dofAperture = fx.DofAperture;

        Parallel.For(0, height, new ParallelOptions { CancellationToken = ct }, y =>
        {
            if (ct.IsCancellationRequested) return;
            double v = (1.0 - 2.0 * (y + 0.5) / height) * fovScale + panV;
            int rowBase = y * width;
            float[] hdrScratch = thinLensDof ? new float[3] : null!;

            uint ShadeRay(double ox, double oy, double oz, double dx, double dy, double dz,
                          out float hr, out float hg, out float hb)
            {
                double sx = ox, sy = oy, sz = oz, tT = 0; bool sHit = false; int sStep = 0;
                for (int step = 0; step < maxSteps; step++)
                {
                    double dist = KleinianDE(sx, sy, sz, gens, deIter, in rot);
                    if (dist < eps) { sHit = true; sStep = step; break; }
                    if (tT > sceneRadius) break;
                    double sstep = dist * deFactor;   // #881 — under-relaxed step
                    sx += dx * sstep; sy += dy * sstep; sz += dz * sstep; tT += sstep;
                }
                if (!sHit)
                {
                    uint sky = fx.ShowSkyBackdrop
                        ? ShadingPipeline.SkyColorHdri(dx, dy, dz, in fx)
                        : ColorMap.InSetColor;
                    hr = ((sky >> 16) & 0xFF) / 255f; hg = ((sky >> 8) & 0xFF) / 255f; hb = (sky & 0xFF) / 255f;
                    return sky;
                }
                double hn = eps * 2;
                double sn0 = KleinianDE(sx + hn, sy, sz, gens, deIter, in rot)
                           - KleinianDE(sx - hn, sy, sz, gens, deIter, in rot);
                double sn1 = KleinianDE(sx, sy + hn, sz, gens, deIter, in rot)
                           - KleinianDE(sx, sy - hn, sz, gens, deIter, in rot);
                double sn2 = KleinianDE(sx, sy, sz + hn, gens, deIter, in rot)
                           - KleinianDE(sx, sy, sz - hn, gens, deIter, in rot);
                var snrm = Normalize3(sn0, sn1, sn2);
                float ssmooth = (float)sStep * (192f / Math.Max(1, maxSteps)) + (float)(tT * 0.5);
                if (colorSrc != KleinianColorSource.Smooth)   // #878 — sample the word just inside the surface
                    ssmooth = KleinianColorScalar(colorSrc, sx + dx * eps * 4, sy + dy * eps * 4, sz + dz * eps * 4, gens, deIter, in rot);
                uint sbase = (uint)ColorMap.Map(ssmooth, 0f, 256, (float)snrm[0], (float)snrm[1]);
                var sinputs = new ShadingInputs(sx, sy, sz, snrm[0], snrm[1], snrm[2], dx, dy, dz, tT, 0.0, sStep, eps);
                ScreenSpacePost.ClearHdrBuffer(hdrScratch);
                uint col = ShadingPipeline.Shade<De>(
                    in sinputs, sbase, in fx, in deStruct, true, 0, null, null, hdrScratch);
                if (!float.IsNaN(hdrScratch[0])) { hr = hdrScratch[0]; hg = hdrScratch[1]; hb = hdrScratch[2]; }
                else { hr = ((col >> 16) & 0xFF) / 255f; hg = ((col >> 8) & 0xFF) / 255f; hb = (col & 0xFF) / 255f; }
                return col;
            }

            for (int x = 0; x < width; x++)
            {
                double u = (2.0 * (x + 0.5) / width - 1.0) * fovScale * aspect + panU;
                double rdx = right[0] * u + up[0] * v + fwd[0];
                double rdy = right[1] * u + up[1] * v + fwd[1];
                double rdz = right[2] * u + up[2] * v + fwd[2];
                var dn = Normalize3(rdx, rdy, rdz);
                rdx = dn[0]; rdy = dn[1]; rdz = dn[2];

                if (thinLensDof)
                {
                    ThinLensDof.AccumulatePixel(
                        x, y, rowBase + x, dofN, 13,
                        camPX, camPY, camPZ, rdx, rdy, rdz,
                        right[0], right[1], right[2], up[0], up[1], up[2],
                        dofFocus, dofAperture, renderBuffer, hdrBuf, ShadeRay);
                    continue;
                }

                double px = camPX, py = camPY, pz = camPZ;
                double tTotal = 0;
                bool hit = false;
                int hitStep = 0;

                for (int step = 0; step < maxSteps; step++)
                {
                    double dist = KleinianDE(px, py, pz, gens, deIter, in rot);
                    if (dist < eps) { hit = true; hitStep = step; break; }
                    if (tTotal > sceneRadius) break;
                    double mstep = dist * deFactor;   // #881 — under-relaxed step
                    px += rdx * mstep; py += rdy * mstep; pz += rdz * mstep;
                    tTotal += mstep;
                }

                int idx = rowBase + x;
                if (!hit)
                {
                    // Ray-miss → sky backdrop when toggle on; InSetColor off (see MandelbulbCalculator).
                    renderBuffer[idx] = fx.ShowSkyBackdrop
                        ? ShadingPipeline.SkyColorHdri(rdx, rdy, rdz, in fx)
                        : ColorMap.InSetColor;
                    continue;
                }

                double h = eps * 2;
                double n0 = KleinianDE(px + h, py, pz, gens, deIter, in rot)
                          - KleinianDE(px - h, py, pz, gens, deIter, in rot);
                double n1 = KleinianDE(px, py + h, pz, gens, deIter, in rot)
                          - KleinianDE(px, py - h, pz, gens, deIter, in rot);
                double n2 = KleinianDE(px, py, pz + h, gens, deIter, in rot)
                          - KleinianDE(px, py, pz - h, gens, deIter, in rot);
                var nrm = Normalize3(n0, n1, n2);

                float smooth = (float)hitStep * (192f / Math.Max(1, maxSteps))
                             + (float)(tTotal * 0.5);
                if (colorSrc != KleinianColorSource.Smooth)   // #878 — sample the word just inside the surface
                    smooth = KleinianColorScalar(colorSrc, px + rdx * eps * 4, py + rdy * eps * 4, pz + rdz * eps * 4, gens, deIter, in rot);
                uint baseColor = (uint)ColorMap.Map(smooth, 0f, 256, (float)nrm[0], (float)nrm[1]);

                // Phase 2 — shading via shared pipeline.
                var inputs = new ShadingInputs(
                    px, py, pz, nrm[0], nrm[1], nrm[2],
                    rdx, rdy, rdz, tTotal, 0.0, hitStep, eps);
                renderBuffer[idx] = ShadingPipeline.Shade<De>(
                    in inputs, baseColor, in fx, in deStruct, true,
                    idx, depthBuf, normalBuf, hdrBuf);
            }
        });

        // Thin-lens DoF integrates the lens + skips the G-buffer → bypass the
        // screen-space passes keyed on it; tonemap/bloom still consume the HDR.
        ScreenSpacePost.BeginGpuFrame(renderBuffer, width, height, in fx);
        if (depthBuf is not null && normalBuf is not null && !thinLensDof)
            ScreenSpacePost.ApplySsao(renderBuffer, depthBuf, normalBuf, width, height, in fx);
        if (hdrBuf is not null && depthBuf is not null && !thinLensDof)
            ScreenSpacePost.ApplyHdrDof(hdrBuf, depthBuf, width, height, in fx);
        if (hdrBuf is not null)
            ScreenSpacePost.ApplyToneMapBloom(renderBuffer, hdrBuf, width, height, in fx);
        if (depthBuf is not null && normalBuf is not null && !thinLensDof)
            ScreenSpacePost.ApplyEdgeInk(renderBuffer, depthBuf, normalBuf, width, height, in fx);
        ScreenSpacePost.EndGpuFrame(in fx);

        if (lowRes)
            FracturingFog.Rendering.LowResPreview.UpscaleNearest(
                renderBuffer, width, height, ColorBuffer, fullW, fullH);

        // #84 — light-direction compass / param bars / scene clock. Standalone
        // final pass on the composited full-res buffer so it survives both the
        // low-res upscale and the GPU-raymarch early-out. Self-guards on flags.
        ScreenSpacePost.ApplyDebugHud(ColorBuffer, fullW, fullH, in fx);
    }

    /// <summary>
    /// Sphere-inversion distance estimator. Iterate "invert through deepest
    /// containing sphere" until the sample point falls outside every sphere,
    /// tracking the scalar inversion-scale product as the chain-rule
    /// derivative magnitude. DE = signed nearest-sphere distance / accumulated
    /// scale.
    /// </summary>
    /// <summary>P3 — concrete DE struct. Holds references to the sphere
    /// centre arrays + tangent radius; iter loop runs inside KleinianDE.</summary>
    public readonly struct De
        : FracturingFog.Rendering.Lighting.IDistanceEstimator,
          FracturingFog.Rendering.Lighting.IOrbitTrapEstimator
    {
        private readonly KleinianGenerator[] _gens;
        private readonly int _iter;
        private readonly KleinianRotation _rot;
        public De(KleinianGenerator[] gens, int iter)
        { _gens = gens; _iter = iter; _rot = KleinianRotation.None; }
        public De(KleinianGenerator[] gens, int iter, KleinianRotation rot)
        { _gens = gens; _iter = iter; _rot = rot; }
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public double Evaluate(double x, double y, double z)
            => KleinianDE(x, y, z, _gens, _iter, in _rot);

        // Orbit trap (roadmap S9, #391): closest the inversion orbit passes to a
        // sphere boundary, normalized by the sphere radius. The natural trap for a
        // sphere-inversion IFS; view-independent mesh colour driver.
        public double OrbitTrap(double x, double y, double z)
            => KleinianTrap(x, y, z, _gens, _iter, in _rot);
    }

    // #877 — Rodrigues rotation of the descent point about the fold axis.
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    private static void RotateInPlace(in KleinianRotation rot, ref double px, ref double py, ref double pz)
    {
        double kv = rot.Ax * px + rot.Ay * py + rot.Az * pz;
        double kxx = rot.Ay * pz - rot.Az * py;
        double kxy = rot.Az * px - rot.Ax * pz;
        double kxz = rot.Ax * py - rot.Ay * px;
        double om = 1.0 - rot.Cos;
        px = px * rot.Cos + kxx * rot.Sin + rot.Ax * kv * om;
        py = py * rot.Cos + kxy * rot.Sin + rot.Ay * kv * om;
        pz = pz * rot.Cos + kxz * rot.Sin + rot.Az * kv * om;
    }

    /// <summary>Orbit-trap measure over an inversion-generator list — closest the
    /// descent orbit passes to any generator's sphere boundary, normalized by the
    /// first sphere's radius. #874 (S1) generalizes this from the fixed 4-sphere
    /// array to <see cref="KleinianGenerator"/>[]; byte-identical for the
    /// tetrahedral group (uniform radius).</summary>
    public static double KleinianTrap(
        double px, double py, double pz,
        KleinianGenerator[] gens, int iter)
        => KleinianTrap(px, py, pz, gens, iter, KleinianRotation.None);

    public static double KleinianTrap(
        double px, double py, double pz,
        KleinianGenerator[] gens, int iter, in KleinianRotation rot)
    {
        int n = gens.Length;
        double normR = n > 0 ? gens[0].R : 1.0;
        double minBoundary = double.MaxValue;
        for (int i = 0; i < iter; i++)
        {
            int bestK = -1;
            double bestDeep = 0.0;
            for (int k = 0; k < n; k++)
            {
                var g = gens[k];
                double dx = px - g.Cx, dy = py - g.Cy, dz = pz - g.Cz;
                double d = Math.Sqrt(dx * dx + dy * dy + dz * dz) - g.R;
                double a = Math.Abs(d);
                if (a < minBoundary) minBoundary = a;
                if (d < bestDeep) { bestDeep = d; bestK = k; }
            }
            if (bestK < 0) break;
            var b = gens[bestK];
            double ex = px - b.Cx, ey = py - b.Cy, ez = pz - b.Cz;
            double e2 = ex * ex + ey * ey + ez * ez;
            if (e2 < 1e-30) break;
            double f = (b.R * b.R) / e2;
            px = b.Cx + ex * f; py = b.Cy + ey * f; pz = b.Cz + ez * f;
            if (rot.Has) RotateInPlace(in rot, ref px, ref py, ref pz);   // #877
        }
        return Math.Clamp(minBoundary / Math.Max(normR, 1e-9), 0.0, 1.0);
    }

    /// <summary>Sphere-inversion distance estimator over an inversion-generator
    /// list: iterate "invert through the deepest containing sphere" until the
    /// sample point escapes every sphere, tracking the scalar inversion-scale
    /// product as the chain-rule derivative magnitude; DE = nearest sphere
    /// boundary / accumulated scale. #874 (S1) generalizes this from the fixed
    /// 4-sphere array to <see cref="KleinianGenerator"/>[] (each generator carries
    /// its own radius); byte-identical for the tetrahedral group.</summary>
    public static double KleinianDE(
        double px, double py, double pz,
        KleinianGenerator[] gens, int iter)
        => KleinianDE(px, py, pz, gens, iter, KleinianRotation.None);

    public static double KleinianDE(
        double px, double py, double pz,
        KleinianGenerator[] gens, int iter, in KleinianRotation rot)
    {
        double scale = 1.0;
        int n = gens.Length;

        for (int i = 0; i < iter; i++)
        {
            // Find sphere whose interior most-contains p (largest negative
            // signed distance). If every signed distance is non-negative, p is
            // outside all spheres → escape.
            int bestK = -1;
            double bestDeep = 0.0;          // most-negative signed distance
            for (int k = 0; k < n; k++)
            {
                var g = gens[k];
                double dx = px - g.Cx;
                double dy = py - g.Cy;
                double dz = pz - g.Cz;
                double d = Math.Sqrt(dx * dx + dy * dy + dz * dz) - g.R;
                if (d < bestDeep) { bestDeep = d; bestK = k; }
            }
            if (bestK < 0) break;

            var b = gens[bestK];
            double ex = px - b.Cx;
            double ey = py - b.Cy;
            double ez = pz - b.Cz;
            double e2 = ex * ex + ey * ey + ez * ez;
            if (e2 < 1e-30) break;
            double f = (b.R * b.R) / e2;
            scale *= f;
            px = b.Cx + ex * f;
            py = b.Cy + ey * f;
            pz = b.Cz + ez * f;
            // #877 — rotation fold (orthogonal → no scale change). Skipped when
            // rot.Has is false, keeping the un-rotated DE byte-identical.
            if (rot.Has) RotateInPlace(in rot, ref px, ref py, ref pz);
        }

        // After escape, return distance to the nearest sphere boundary in
        // post-iteration space, scaled back to world space by the accumulated
        // inversion derivative.
        double nearest = double.PositiveInfinity;
        for (int k = 0; k < n; k++)
        {
            var g = gens[k];
            double dx = px - g.Cx;
            double dy = py - g.Cy;
            double dz = pz - g.Cz;
            double d = Math.Sqrt(dx * dx + dy * dy + dz * dz) - g.R;
            double a = Math.Abs(d);
            if (a < nearest) nearest = a;
        }
        if (scale < 1e-30) return 0.0;
        return nearest / scale;
    }

    /// <summary>#878 — run the inversion descent at a point and report the word:
    /// <paramref name="depth"/> = number of inversion steps executed before escape,
    /// <paramref name="lastGen"/> = index of the last generator applied (−1 if none).
    /// Mirrors <see cref="KleinianDE"/>'s loop; drives WordLength / LastGenerator
    /// colouring, and makes <c>KleinianIterations</c> visible (#53).</summary>
    public static void KleinianWord(
        double px, double py, double pz,
        KleinianGenerator[] gens, int iter, in KleinianRotation rot,
        out int depth, out int lastGen)
    {
        int n = gens.Length;
        depth = 0; lastGen = -1;
        for (int i = 0; i < iter; i++)
        {
            int bestK = -1;
            double bestDeep = 0.0;
            for (int k = 0; k < n; k++)
            {
                var g = gens[k];
                double dx = px - g.Cx, dy = py - g.Cy, dz = pz - g.Cz;
                double d = Math.Sqrt(dx * dx + dy * dy + dz * dz) - g.R;
                if (d < bestDeep) { bestDeep = d; bestK = k; }
            }
            if (bestK < 0) break;
            var b = gens[bestK];
            double ex = px - b.Cx, ey = py - b.Cy, ez = pz - b.Cz;
            double e2 = ex * ex + ey * ey + ez * ez;
            if (e2 < 1e-30) break;
            double f = (b.R * b.R) / e2;
            px = b.Cx + ex * f; py = b.Cy + ey * f; pz = b.Cz + ez * f;
            if (rot.Has) RotateInPlace(in rot, ref px, ref py, ref pz);
            depth++; lastGen = bestK;
        }
    }

    // #878 — the palette scalar [0,256) for the selected colour source at a hit.
    private static float KleinianColorScalar(
        KleinianColorSource src, double px, double py, double pz,
        KleinianGenerator[] gens, int iter, in KleinianRotation rot)
    {
        KleinianWord(px, py, pz, gens, iter, in rot, out int depth, out int lastGen);
        if (src == KleinianColorSource.LastGenerator)
        {
            int n = Math.Max(1, gens.Length);
            int g = lastGen < 0 ? 0 : lastGen;
            return (float)((g + 0.5) / n * 256.0);
        }
        // WordLength — band by descent depth over the iteration cap.
        float wl = (float)depth / Math.Max(1, iter);
        return wl * 255.0f;
    }

    private static double[] Normalize3(double x, double y, double z)
    {
        double len = Math.Sqrt(x * x + y * y + z * z);
        if (len < 1e-10) return new[] { 0.0, 0.0, 0.0 };
        return new[] { x / len, y / len, z / len };
    }
}
