<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <Optimize>true</Optimize>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>FracturingFog</AssemblyName>
    <RootNamespace>FracturingFog</RootNamespace>
    <GenerateDocumentationFile>False</GenerateDocumentationFile>
    <Configurations>Debug;Release;Publish</Configurations>
    <ProduceReferenceAssembly>False</ProduceReferenceAssembly>
    <Title>Fracturing Fog</Title>
    <ApplicationIcon>Resources\FracturingFog.ico</ApplicationIcon>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <DebugType>full</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <DebugType>full</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Publish|x64'">
    <DebugType>full</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="formmain.txt" />
    <None Remove="MainForm - Copy.cs.20260416-" />
    <None Remove="MainForm - Copy.cs.orig" />
    <None Remove="MNDD3D-VRT383.zip" />
    <None Remove="Resources\FFLogo.bmp" />
    <None Remove="Resources\FFLogo.png" />
    <None Remove="Resources\ResolutionRatios.txt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\FracturingFog.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="C:\Users\bradl\Documents\regions.json" Link="Resources\regions.json" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Vortice.Direct3D11" Version="3.8.3" />
    <PackageReference Include="Vortice.Direct3D12" Version="3.8.3" />
    <PackageReference Include="Vortice.DirectX" Version="3.8.3" />
    <PackageReference Include="Vortice.DXGI" Version="3.8.3" />
    <PackageReference Include="Vortice.D3DCompiler" Version="3.8.3" />
    <PackageReference Include="Vortice.Mathematics" Version="2.1.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Resources\colorthemes.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\ColorThemes\colorthemes.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\ColorThemes\colorthemes.json.20260513">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\copythemesregions.bat">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\FracturingFog.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\regions.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\regions.json.20260514">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\reset.bmp">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\reset.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Tools\ffmpeg.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Tools\" />
  </ItemGroup>

</Project>
