// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Bradley Brown

// Abstractions/Cli/ShellQuoting.cs
// #999 (CB7 of #64) — quote a batch command for the shell it will be pasted
// into, and wrap it as a script file. The historic BatchCommandBuilder.Token
// quoting ("…" with \" escapes) is bash-flavoured and wrong for PowerShell
// (# starts a comment, a comma builds an array, $ interpolates inside "…") and
// for cmd (a trailing backslash before the closing quote escapes it).

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace FracturingFog.Cli
{
    /// <summary>The shell a command line is written for.</summary>
    public enum CommandShell
    {
        /// <summary>Windows PowerShell 5.1 / PowerShell 7 (single-quoted literals).</summary>
        PowerShell,
        /// <summary>cmd.exe — double quotes, argv rules of the C runtime.</summary>
        Cmd,
        /// <summary>POSIX sh / bash / zsh (single-quoted literals).</summary>
        Bash,
    }

    public static class ShellQuoting
    {
        /// <summary>The platform's natural shell: PowerShell on Windows, else bash.</summary>
        public static CommandShell Default
            => OperatingSystem.IsWindows() ? CommandShell.PowerShell : CommandShell.Bash;

        /// <summary>Script file extension for <paramref name="shell"/>.</summary>
        public static string ScriptExtension(CommandShell shell) => shell switch
        {
            CommandShell.PowerShell => ".ps1",
            CommandShell.Cmd        => ".cmd",
            _                       => ".sh",
        };

        /// <summary>Quote one argument so <paramref name="shell"/> hands the
        /// program exactly <paramref name="value"/>.</summary>
        public static string Quote(string value, CommandShell shell)
        {
            value ??= "";
            return shell switch
            {
                CommandShell.PowerShell => QuotePowerShell(value),
                CommandShell.Cmd        => QuoteCmd(value),
                _                       => QuoteBash(value),
            };
        }

        /// <summary>The full command line: executable, <c>--batch</c>, then the
        /// arguments, each quoted for <paramref name="shell"/>. A quoted
        /// executable in PowerShell is invoked with the call operator (<c>&amp;</c>).</summary>
        public static string Join(string executable, IEnumerable<string> args, CommandShell shell)
        {
            string exe = Quote(executable, shell);
            var sb = new StringBuilder();
            if (shell == CommandShell.PowerShell && exe != executable) sb.Append("& ");
            sb.Append(exe).Append(" --batch");
            foreach (var a in args) sb.Append(' ').Append(Quote(a, shell));
            return sb.ToString();
        }

        /// <summary>A runnable script for the command line (already joined for
        /// <paramref name="shell"/>). It propagates the batch exit code.</summary>
        public static string Script(string commandLine, CommandShell shell)
        {
            const string header = "Fracturing Fog batch command (generated by the Command Builder)";
            return shell switch
            {
                CommandShell.PowerShell =>
                    "# " + header + "\r\n" + commandLine + "\r\nexit $LASTEXITCODE\r\n",
                // A .cmd file expands %VAR% even inside quotes; %% is a literal %.
                CommandShell.Cmd =>
                    "@echo off\r\nrem " + header + "\r\n" + commandLine.Replace("%", "%%") + "\r\nexit /b %ERRORLEVEL%\r\n",
                _ =>
                    "#!/usr/bin/env bash\n# " + header + "\n" + commandLine + "\n",
            };
        }

        // Characters that never need quoting in any of the shells (and do not
        // start a comment / option-like special when leading).
        private static bool IsPlain(char c)
            => char.IsAsciiLetterOrDigit(c) || c is '-' or '_' or '.' or '/' or ':' or '+' or '=';

        private static bool AllPlain(string v) => v.Length > 0 && v.All(IsPlain);

        // POSIX: '…' is fully literal; a ' is written as '\''.
        private static string QuoteBash(string v)
            => AllPlain(v) ? v : "'" + v.Replace("'", "'\\''") + "'";

        // PowerShell: '…' is fully literal; a ' is written as ''. Bare words are
        // only safe from the plain set ( # , ; $ @ ` ( ) { } & | < > and quotes all
        // mean something). A leading - keeps working for native commands.
        private static string QuotePowerShell(string v)
            => AllPlain(v) ? v : "'" + v.Replace("'", "''") + "'";

        // cmd.exe: wrap in "…" and escape per the C-runtime argv rules the target
        // parses with — backslashes are literal except before a quote, where 2n
        // backslashes + \" encode n backslashes + a quote, and a trailing run
        // before the closing quote is doubled.
        private static string QuoteCmd(string v)
        {
            if (AllPlain(v) && !v.Contains('\\')) return v;
            if (AllPlainOrBackslash(v)) return v;   // C:\x\y — no quotes needed
            var sb = new StringBuilder("\"");
            int backslashes = 0;
            foreach (char c in v)
            {
                if (c == '\\') { backslashes++; continue; }
                if (c == '"')
                {
                    sb.Append('\\', backslashes * 2 + 1).Append('"');
                }
                else
                {
                    sb.Append('\\', backslashes).Append(c);
                }
                backslashes = 0;
            }
            sb.Append('\\', backslashes * 2).Append('"');
            return sb.ToString();
        }

        private static bool AllPlainOrBackslash(string v)
            => v.Length > 0 && v.All(c => IsPlain(c) || c == '\\');
    }
}
