// Services/Exporters/CssVariablesExporter.cs
//
// CSS custom-property block. Names sequentially as --palette-01 etc so the
// caller can :root them and use var(--palette-N) downstream.

using System.Collections.Generic;
using System.IO;
using System.Text;
using FracturingFog.Imaging;

namespace PaletteBuilder.Services.Exporters
{
    public sealed class CssVariablesExporter : IPaletteExporter
    {
        public string Id => "css";
        public string DisplayName => "CSS variables";
        public string Extension => "css";

        public void Export(string path,
                           IReadOnlyList<(byte R, byte G, byte B)> swatches,
                           IReadOnlyList<PaletteStop>? stops = null,
                           PaletteExportContext? context = null)
        {
            var sb = new StringBuilder();
            sb.AppendLine("/* " + (context?.PaletteName ?? "Palette") + " — generated by Palette Builder */");
            sb.AppendLine(":root {");
            for (int i = 0; i < swatches.Count; i++)
            {
                var c = swatches[i];
                sb.Append($"  --palette-{(i + 1):00}: #{c.R:X2}{c.G:X2}{c.B:X2};");
                sb.AppendLine($"   /* rgb({c.R}, {c.G}, {c.B}) */");
            }
            sb.AppendLine("}");
            File.WriteAllText(path, sb.ToString());
        }
    }
}
