// Services/Exporters/ScssMapExporter.cs
//
// SCSS map: $palette: (01: #aabbcc, 02: #112233, ...);
// Lets Sass consumers use map-get($palette, "01") downstream.

using System.Collections.Generic;
using System.IO;
using System.Text;
using FracturingFog.Imaging;

namespace PaletteBuilder.Services.Exporters
{
    public sealed class ScssMapExporter : IPaletteExporter
    {
        public string Id => "scss";
        public string DisplayName => "SCSS map";
        public string Extension => "scss";

        public void Export(string path,
                           IReadOnlyList<(byte R, byte G, byte B)> swatches,
                           IReadOnlyList<PaletteStop>? stops = null,
                           PaletteExportContext? context = null)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// " + (context?.PaletteName ?? "Palette") + " — generated by Palette Builder");
            sb.AppendLine("$palette: (");
            for (int i = 0; i < swatches.Count; i++)
            {
                var c = swatches[i];
                string sep = i == swatches.Count - 1 ? "" : ",";
                sb.AppendLine($"  \"{(i + 1):00}\": #{c.R:X2}{c.G:X2}{c.B:X2}{sep}");
            }
            sb.AppendLine(");");
            File.WriteAllText(path, sb.ToString());
        }
    }
}
