// MandelbrotZ2Calculator.cs — GENERATED by CalculatorGen
//
// Source equation (z, c complex):
//     z_{n+1} = z*z + c
//
// Symbolic derivatives (auto-derived):
//     ∂p/∂z = z + z
//     ∂p/∂c = 1
//
// Per-iteration derivative recurrence (used for Inigo Quilez surface
// normals and the exterior distance estimate):
//
//     dz_{n+1}/dc  =  (∂p/∂z) · (dz_n/dc)  +  (∂p/∂c)
//                  =  (z + z)*D + 1
//
// Generator: CalculatorGen v0.2 (polynomial + symbolic-diff emitter)
// Generated: 2026-05-31 15:06:55 UTC
//
// DO NOT HAND-EDIT. Re-run CalculatorGen with the same --name flag to
// regenerate. If you need behaviour the generator cannot produce
// (transcendentals, abs-fold, conditional branches), copy this file,
// rename the class, and remove this banner.
//
// Implementation notes
// ──────────────────────────────────────────────────────────────────────
//   • Scalar path: portable double-precision, one pixel at a time. Used
//     as the correctness reference and as the fallback when AVX2+FMA is
//     unavailable.
//   • AVX2 path:  Vector256<double> (4 pixels per lane). Complex multiply
//     uses Fma.MultiplyAdd / MultiplyAddNegated pairs.
//   • Derivative tracking: dz/dc is updated alongside z every iteration.
//     At escape it feeds two colour-map inputs:
//       - nx, ny = unit normal to the escape-potential level curve
//                  (Inigo Quilez:  z · conj(dz/dc), normalised)
//       - distance = exterior distance estimate
//                    (Milnor / Hubbard:  0.5 · |z| · log|z| / |dz/dc|)
//   • Raw helpers (IteratePixelScalarRaw / IterateLaneAvx2Raw) expose
//     iteration counts without colour; used by MandelbrotZ2CalculatorSelfTest
//     to validate scalar ↔ AVX2 agreement.
//
// Future tiers (sketched in Docs/CalculatorGen-Authoring.md)
//   • Tier 3: double-double SIMD (deep zoom)
//   • Tier 4: perturbation + reference orbit (derivative is the
//             linearised term; the same AST drives Taylor expansion)
//   • Tier 5: BLA tables, Series Approximation prelude
//   • Tier 6: ILGPU GPU kernel

using System;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using System.Threading;
using System.Threading.Tasks;

using FracturingFog.Interefaces;
using FracturingFog.Models;

namespace FracturingFog.Calculators.Generated;

public sealed class MandelbrotZ2Calculator : IFractalCalculator
{
    public int Width  { get; private set; }
    public int Height { get; private set; }
    public uint[] ColorBuffer { get; private set; } = Array.Empty<uint>();

    public double CenterX { get; set; } = 0.0;
    public double CenterY { get; set; } = 0.0;
    public double Zoom    { get; set; } = 1.0;
    public int MaxIterations { get; set; } = 512;

    public QualityPreset Quality { get; set; } = QualityPreset.Standard;
    public IColorMap ColorMap { get; set; } = new HsvPalette();

    public bool SupportsZoomPan => true;

    // Bailout radius². Generous default; tighten if the equation has a
    // smaller natural escape boundary.
    private const double Bailout2 = 1024.0;

    // Pixel scale recorded at Calculate entry; the colour map's
    // distance-estimation themes need it to normalise raw exterior
    // distance to pixels.
    private double _lastPixelScale = 1.0;

    public MandelbrotZ2Calculator(int width, int height) => Resize(width, height);

    public void Resize(int width, int height)
    {
        Width  = width;
        Height = height;
        ColorBuffer = new uint[width * height];
    }

    public void Calculate(CancellationToken ct = default)
    {
        ColorMap.MaxIterations = MaxIterations;
        double scale = (3.5 / Math.Max(Width, Height)) / Zoom;
        _lastPixelScale = scale;
        bool useAvx = Avx2.IsSupported && Fma.IsSupported && Width >= 4;

        Parallel.For(0, Height, new ParallelOptions { CancellationToken = ct }, y =>
        {
            if (ct.IsCancellationRequested) return;
            double dy = (y - Height * 0.5) * scale;
            double ciScalar = CenterY + dy;
            int rowBase = y * Width;
            int x = 0;
            if (useAvx)
            {
                var ciVec = Vector256.Create(ciScalar);
                for (; x + 4 <= Width; x += 4)
                {
                    double cx0 = CenterX + (x     - Width * 0.5) * scale;
                    double cx1 = CenterX + (x + 1 - Width * 0.5) * scale;
                    double cx2 = CenterX + (x + 2 - Width * 0.5) * scale;
                    double cx3 = CenterX + (x + 3 - Width * 0.5) * scale;
                    var crVec = Vector256.Create(cx0, cx1, cx2, cx3);
                    IterateLaneAvx2(crVec, ciVec, ColorBuffer, rowBase + x);
                }
            }
            for (; x < Width; x++)
            {
                double cx = CenterX + (x - Width * 0.5) * scale;
                IteratePixelScalar(cx, ciScalar, ColorBuffer, rowBase + x);
            }
        });
    }

    // ── Scalar (reference) path ─────────────────────────────────────────────

    private void IteratePixelScalar(double cr, double ci, uint[] buf, int idx)
    {
        double zr = 0.0, zi = 0.0;
        double dr = 0.0, di = 0.0;
        int it = 0;
        int maxIt = MaxIterations;
        for (; it < maxIt; it++)
        {
            double r2 = zr * zr + zi * zi;
            if (r2 >= Bailout2) break;
            double dr_new = (((zr + zr) * dr - (zi + zi) * di) + 1.0);
            double di_new = ((zr + zr) * di + (zi + zi) * dr);
            double zr_new = ((zr * zr - zi * zi) + cr);
            double zi_new = ((zr * zi + zi * zr) + ci);
            zr = zr_new; zi = zi_new;
            dr = dr_new; di = di_new;
        }
        buf[idx] = ColorFor(it, zr, zi, dr, di, maxIt);
    }

    // Iteration-count-only variant (no colour writeback). Used by the
    // self-test to compare the AVX2 path against the scalar reference.
    internal int IteratePixelScalarRaw(double cr, double ci,
                                       out double zrOut, out double ziOut,
                                       out double drOut, out double diOut)
    {
        double zr = 0.0, zi = 0.0;
        double dr = 0.0, di = 0.0;
        int it = 0;
        int maxIt = MaxIterations;
        for (; it < maxIt; it++)
        {
            double r2 = zr * zr + zi * zi;
            if (r2 >= Bailout2) break;
            double dr_new = (((zr + zr) * dr - (zi + zi) * di) + 1.0);
            double di_new = ((zr + zr) * di + (zi + zi) * dr);
            double zr_new = ((zr * zr - zi * zi) + cr);
            double zi_new = ((zr * zi + zi * zr) + ci);
            zr = zr_new; zi = zi_new;
            dr = dr_new; di = di_new;
        }
        zrOut = zr; ziOut = zi; drOut = dr; diOut = di;
        return it;
    }

    // ── AVX2 path (4 pixels per lane) ───────────────────────────────────────

    private void IterateLaneAvx2(Vector256<double> cr, Vector256<double> ci, uint[] buf, int idx)
    {
        Vector256<double> zr = Vector256<double>.Zero;
        Vector256<double> zi = Vector256<double>.Zero;
        Vector256<double> dr = Vector256<double>.Zero;
        Vector256<double> di = Vector256<double>.Zero;
        Vector256<double> bailoutVec = Vector256.Create(Bailout2);
        Vector256<long> itCounts = Vector256<long>.Zero;
        Vector256<long> oneL = Vector256.Create(1L);
        Vector256<long> activeLanes = Vector256.Create(-1L);   // all lanes active initially

        int maxIt = MaxIterations;
        for (int n = 0; n < maxIt; n++)
        {
            var r2 = Fma.MultiplyAdd(zr, zr, Avx.Multiply(zi, zi));
            // active = (r2 < bailout) — lanes that have NOT yet escaped
            var activeMaskD = Avx.Compare(r2, bailoutVec, FloatComparisonMode.OrderedLessThanNonSignaling);
            var activeMaskL = activeMaskD.AsInt64();
            activeLanes = Avx2.And(activeLanes, activeMaskL);
            if (Avx.MoveMask(activeMaskD) == 0) break;
            itCounts = Avx2.Add(itCounts, Avx2.And(oneL, activeMaskL));

                Vector256<double> d_re1 = Avx.Add(zr, zr);
                Vector256<double> d_im2 = Avx.Add(zi, zi);
                Vector256<double> d_re3 = Fma.MultiplyAddNegated(d_im2, di, Avx.Multiply(d_re1, dr));
                Vector256<double> d_im4 = Fma.MultiplyAdd(d_re1, di, Avx.Multiply(d_im2, dr));
                Vector256<double> d_re5 = Vector256.Create(1.0);
                Vector256<double> d_re6 = Avx.Add(d_re3, d_re5);
                Vector256<double> dr_new = d_re6;
                Vector256<double> di_new = d_im4;
                Vector256<double> z_re1 = Fma.MultiplyAddNegated(zi, zi, Avx.Multiply(zr, zr));
                Vector256<double> z_im2 = Fma.MultiplyAdd(zr, zi, Avx.Multiply(zi, zr));
                Vector256<double> z_re3 = Avx.Add(z_re1, cr);
                Vector256<double> z_im4 = Avx.Add(z_im2, ci);
                Vector256<double> zr_new = z_re3;
                Vector256<double> zi_new = z_im4;

            // Freeze z, dz/dc for any lane that escaped this iteration; live
            // lanes pick up the new values.
            var keepD = activeMaskL.AsDouble();
            zr = Avx.BlendVariable(zr, zr_new, keepD);
            zi = Avx.BlendVariable(zi, zi_new, keepD);
            dr = Avx.BlendVariable(dr, dr_new, keepD);
            di = Avx.BlendVariable(di, di_new, keepD);
        }

        Span<long> its = stackalloc long[4];
        Span<double> zrs = stackalloc double[4];
        Span<double> zis = stackalloc double[4];
        Span<double> drs = stackalloc double[4];
        Span<double> dis = stackalloc double[4];
        itCounts.CopyTo(its);
        zr.CopyTo(zrs); zi.CopyTo(zis);
        dr.CopyTo(drs); di.CopyTo(dis);
        for (int k = 0; k < 4; k++)
            buf[idx + k] = ColorFor((int)its[k], zrs[k], zis[k], drs[k], dis[k], MaxIterations);
    }

    // Iteration-count-only variant for the self-test (no colour writeback).
    internal void IterateLaneAvx2Raw(Vector256<double> cr, Vector256<double> ci,
                                      Span<int> outIters)
    {
        Vector256<double> zr = Vector256<double>.Zero;
        Vector256<double> zi = Vector256<double>.Zero;
        Vector256<double> dr = Vector256<double>.Zero;
        Vector256<double> di = Vector256<double>.Zero;
        Vector256<double> bailoutVec = Vector256.Create(Bailout2);
        Vector256<long> itCounts = Vector256<long>.Zero;
        Vector256<long> oneL = Vector256.Create(1L);

        int maxIt = MaxIterations;
        for (int n = 0; n < maxIt; n++)
        {
            var r2 = Fma.MultiplyAdd(zr, zr, Avx.Multiply(zi, zi));
            var activeMaskD = Avx.Compare(r2, bailoutVec, FloatComparisonMode.OrderedLessThanNonSignaling);
            var activeMaskL = activeMaskD.AsInt64();
            if (Avx.MoveMask(activeMaskD) == 0) break;
            itCounts = Avx2.Add(itCounts, Avx2.And(oneL, activeMaskL));

                Vector256<double> d_re1 = Avx.Add(zr, zr);
                Vector256<double> d_im2 = Avx.Add(zi, zi);
                Vector256<double> d_re3 = Fma.MultiplyAddNegated(d_im2, di, Avx.Multiply(d_re1, dr));
                Vector256<double> d_im4 = Fma.MultiplyAdd(d_re1, di, Avx.Multiply(d_im2, dr));
                Vector256<double> d_re5 = Vector256.Create(1.0);
                Vector256<double> d_re6 = Avx.Add(d_re3, d_re5);
                Vector256<double> dr_new = d_re6;
                Vector256<double> di_new = d_im4;
                Vector256<double> z_re1 = Fma.MultiplyAddNegated(zi, zi, Avx.Multiply(zr, zr));
                Vector256<double> z_im2 = Fma.MultiplyAdd(zr, zi, Avx.Multiply(zi, zr));
                Vector256<double> z_re3 = Avx.Add(z_re1, cr);
                Vector256<double> z_im4 = Avx.Add(z_im2, ci);
                Vector256<double> zr_new = z_re3;
                Vector256<double> zi_new = z_im4;

            var keepD = activeMaskL.AsDouble();
            zr = Avx.BlendVariable(zr, zr_new, keepD);
            zi = Avx.BlendVariable(zi, zi_new, keepD);
            dr = Avx.BlendVariable(dr, dr_new, keepD);
            di = Avx.BlendVariable(di, di_new, keepD);
        }

        Span<long> its = stackalloc long[4];
        itCounts.CopyTo(its);
        for (int k = 0; k < 4; k++) outIters[k] = (int)its[k];
    }

    // ── Colour mapping ──────────────────────────────────────────────────────
    //
    // Uses the nine-parameter IColorMap.Map overload so themes get smooth
    // count, distance estimate, normal direction, final z, and final dz/dc.
    // Themes that ignore these inherit the default 3-arg fallback via the
    // interface's default implementations.

    private uint ColorFor(int it, double zr, double zi, double dr, double di, int maxIt)
    {
        if (it >= maxIt) return ColorMap.InSetColor;

        double zMag2 = zr * zr + zi * zi;
        double zMag  = Math.Sqrt(zMag2);
        double dMag2 = dr * dr + di * di;
        double dMag  = Math.Sqrt(dMag2);

        // Smooth iteration count: standard log-log normalisation.
        float smooth = (float)(it + 1.0
            - Math.Log2(Math.Max(1e-10, Math.Log2(Math.Max(zMag, 1.0 + 1e-10)))));

        // Surface normal (Inigo Quilez): u + v·i  ∝  z · conj(dz/dc)
        //   u = zr·dr + zi·di
        //   v = zi·dr − zr·di
        double u = zr * dr + zi * di;
        double v = zi * dr - zr * di;
        double m = Math.Sqrt(u * u + v * v);
        float nx = 0f, ny = 0f;
        if (m > 1e-30) { nx = (float)(u / m); ny = (float)(v / m); }

        // Exterior distance estimate (Milnor / Hubbard):
        //   d ≈ 0.5 · |z| · log|z| / |dz/dc|
        // Returned in complex-plane units; themes scale by _lastPixelScale.
        float distance = 0f;
        if (dMag > 1e-30 && zMag > 1.0)
            distance = (float)(0.5 * zMag * Math.Log(zMag) / dMag);

        return (uint)ColorMap.Map(
            smooth, distance, maxIt, nx, ny,
            (float)zr, (float)zi, (float)dr, (float)di);
    }
}
