// MandelbrotZ2CalculatorSelfTest.cs — GENERATED by CalculatorGen --selftest
//
// Validates that the AVX2 path matches the scalar reference path of
// MandelbrotZ2Calculator on a fixed sample grid. Compares per-pixel iteration
// counts; FMA rounding lets the two paths differ by at most 1 iteration
// at boundary pixels (a single ULP shift in the bailout-radius test),
// so the tolerance is `maxAbsDiff ≤ 1`.
//
// Usage
//   var ok = MandelbrotZ2CalculatorSelfTest.Run(out var report);
//   Console.WriteLine(report);
//
// The sample grid hits the standard Mandelbrot view (center (-0.75, 0),
// span 3.5) at 64×64 resolution. The equation may produce a totally
// different fractal there — that is fine. We are testing path agreement,
// not visual correctness; agreement is independent of where you sample.

using System;
using System.Runtime.Intrinsics;
using System.Text;

namespace FracturingFog.Calculators.Generated;

public static class MandelbrotZ2CalculatorSelfTest
{
    public const int GridWidth  = 64;
    public const int GridHeight = 64;
    public const int Iterations = 256;
    public const int Tolerance  = 1;   // ≤1 iteration count drift per pixel

    public static bool Run(out string report)
    {
        var calc = new MandelbrotZ2Calculator(GridWidth, GridHeight) { MaxIterations = Iterations };

        const double centerX = -0.75;
        const double centerY =  0.0;
        const double span    =  3.5;
        double scale = span / GridWidth;

        int totalPixels = 0;
        int mismatches  = 0;
        int maxAbsDiff  = 0;
        double sumAbsDiff = 0.0;

        Span<int> avxOut = stackalloc int[4];

        for (int y = 0; y < GridHeight; y++)
        {
            double cy = centerY + (y - GridHeight * 0.5) * scale;
            for (int xStart = 0; xStart + 4 <= GridWidth; xStart += 4)
            {
                double cx0 = centerX + (xStart     - GridWidth * 0.5) * scale;
                double cx1 = centerX + (xStart + 1 - GridWidth * 0.5) * scale;
                double cx2 = centerX + (xStart + 2 - GridWidth * 0.5) * scale;
                double cx3 = centerX + (xStart + 3 - GridWidth * 0.5) * scale;

                int s0 = calc.IteratePixelScalarRaw(cx0, cy, out _, out _, out _, out _);
                int s1 = calc.IteratePixelScalarRaw(cx1, cy, out _, out _, out _, out _);
                int s2 = calc.IteratePixelScalarRaw(cx2, cy, out _, out _, out _, out _);
                int s3 = calc.IteratePixelScalarRaw(cx3, cy, out _, out _, out _, out _);

                var crVec = Vector256.Create(cx0, cx1, cx2, cx3);
                var ciVec = Vector256.Create(cy);
                calc.IterateLaneAvx2Raw(crVec, ciVec, avxOut);

                int d0 = Math.Abs(s0 - avxOut[0]);
                int d1 = Math.Abs(s1 - avxOut[1]);
                int d2 = Math.Abs(s2 - avxOut[2]);
                int d3 = Math.Abs(s3 - avxOut[3]);

                foreach (int d in new[] { d0, d1, d2, d3 })
                {
                    totalPixels++;
                    sumAbsDiff += d;
                    if (d > 0) mismatches++;
                    if (d > maxAbsDiff) maxAbsDiff = d;
                }
            }
        }

        bool ok = maxAbsDiff <= Tolerance;

        var sb = new StringBuilder();
        sb.AppendLine($"{nameof(MandelbrotZ2CalculatorSelfTest)} — scalar ↔ AVX2 agreement");
        sb.AppendLine($"  grid:           {GridWidth}×{GridHeight} = {totalPixels} pixels");
        sb.AppendLine($"  max iterations: {Iterations}");
        sb.AppendLine($"  mismatches:     {mismatches} ({(totalPixels == 0 ? 0.0 : 100.0 * mismatches / totalPixels):F2}%)");
        sb.AppendLine($"  mean |Δit|:     {(totalPixels == 0 ? 0.0 : sumAbsDiff / totalPixels):F4}");
        sb.AppendLine($"  max  |Δit|:     {maxAbsDiff}  (tolerance: {Tolerance})");
        sb.AppendLine($"  result:         {(ok ? "PASS" : "FAIL")}");
        report = sb.ToString();
        return ok;
    }
}
