// MandelbrotZ3Calculator.cs — GENERATED by CalculatorGen
//
// Source equation (z, c complex):
//     z_{n+1} = z*z*z + c
//
// Symbolic derivatives (auto-derived):
//     ∂p/∂z = (z + z)*z + z*z
//     ∂p/∂c = 1
//
// Per-iteration derivative recurrence (used for Inigo Quilez surface
// normals and the exterior distance estimate):
//
//     dz_{n+1}/dc  =  (∂p/∂z) · (dz_n/dc)  +  (∂p/∂c)
//                  =  ((z + z)*z + z*z)*D + 1
//
// Generator: CalculatorGen v0.3 (polynomial + symbolic diff + ILGPU)
// Generated: 2026-05-31 15:35:38 UTC
//
// DO NOT HAND-EDIT. Re-run CalculatorGen with the same --name flag to
// regenerate. If you need behaviour the generator cannot produce
// (transcendentals, abs-fold, conditional branches), copy this file,
// rename the class, and remove this banner.
//
// Implementation notes
// ──────────────────────────────────────────────────────────────────────
//   • Scalar path: portable double-precision, one pixel at a time. Used
//     as the correctness reference and as the fallback when AVX2+FMA is
//     unavailable.
//   • AVX2 path:  Vector256<double> (4 pixels per lane). Complex multiply
//     uses Fma.MultiplyAdd / MultiplyAddNegated pairs.
//   • GPU path (Tier 6): ILGPU-compiled kernel issues one work item per
//     pixel. Returns a raw-state buffer (iter + z + dz/dc); the CPU
//     post-pass runs IColorMap.Map across the buffer in parallel, so the
//     theme system is fully honoured. Opt-in via UseGpu = true; lazy
//     accelerator init, falls back to AVX2/scalar on failure.
//   • Perturbation path (Tier 4): reference-orbit double-precision walk
//     plus a δ-iteration kernel built from the symbolic Taylor expansion
//     of p(Z+δ, c+ε) − p(Z, c). Used by the deep-zoom theme when the
//     view's Zoom > _perturbThreshold. Symbolically exact for polynomial
//     equations — no truncation error beyond round-off in the reference
//     orbit's doubles.
//   • BLA tables (Tier 5): per-iteration Bilinear Approximation
//     A_n = ∂p/∂z(Z_n), B_n = ∂p/∂c(Z_n). Active iterations are skipped
//     in bulk when the linearisation is valid.
//   • Derivative tracking: dz/dc is updated alongside z every iteration.
//     At escape it feeds two colour-map inputs:
//       - nx, ny = unit normal to the escape-potential level curve
//                  (Inigo Quilez:  z · conj(dz/dc), normalised)
//       - distance = exterior distance estimate
//                    (Milnor / Hubbard:  0.5 · |z| · log|z| / |dz/dc|)
//   • Raw helpers (IteratePixelScalarRaw / IterateLaneAvx2Raw) expose
//     iteration counts without colour; used by MandelbrotZ3CalculatorSelfTest
//     to validate scalar ↔ AVX2 agreement.

using System;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using System.Threading;
using System.Threading.Tasks;

using ILGPU;
using ILGPU.Runtime;

using FracturingFog.Interefaces;
using FracturingFog.Models;

namespace FracturingFog.Calculators.Generated;

public sealed class MandelbrotZ3Calculator : IFractalCalculator, IDisposable
{
    public int Width  { get; private set; }
    public int Height { get; private set; }
    public uint[] ColorBuffer { get; private set; } = Array.Empty<uint>();

    public double CenterX { get; set; } = 0.0;
    public double CenterY { get; set; } = 0.0;
    public double Zoom    { get; set; } = 1.0;
    public int MaxIterations { get; set; } = 512;

    public QualityPreset Quality { get; set; } = QualityPreset.Standard;
    public IColorMap ColorMap { get; set; } = new HsvPalette();

    public bool SupportsZoomPan => true;

    /// <summary>Opt-in GPU execution. When true, Calculate dispatches to an
    /// ILGPU kernel and falls back to AVX2 if the device is unavailable or
    /// the kernel fails to load.</summary>
    public bool UseGpu { get; set; } = false;

    /// <summary>Opt-in perturbation deep-zoom path. When true and Zoom exceeds
    /// PerturbZoomThreshold, the renderer computes a reference orbit + per-
    /// pixel δ iteration instead of full double-precision iteration. Tier 4.</summary>
    public bool UsePerturbation { get; set; } = false;
    public double PerturbZoomThreshold { get; set; } = 1.0e12;

    /// <summary>Opt-in BLA acceleration (Tier 5). Requires UsePerturbation.</summary>
    public bool UseBla { get; set; } = false;

    // Bailout radius². Generous default; tighten if the equation has a
    // smaller natural escape boundary.
    private const double Bailout2 = 1024.0;

    private double _lastPixelScale = 1.0;

    public MandelbrotZ3Calculator(int width, int height) => Resize(width, height);

    public void Resize(int width, int height)
    {
        Width  = width;
        Height = height;
        ColorBuffer = new uint[width * height];
    }

    public void Calculate(CancellationToken ct = default)
    {
        ColorMap.MaxIterations = MaxIterations;
        double scale = (3.5 / Math.Max(Width, Height)) / Zoom;
        _lastPixelScale = scale;

        // GPU path: opt-in, lazy init, automatic fallback.
        if (UseGpu && TryRenderGpu(scale, ct)) return;

        // Perturbation path: opt-in, only when zoomed in far enough that
        // double precision starts to lose ULPs.
        if (UsePerturbation && Zoom >= PerturbZoomThreshold && TryRenderPerturbation(scale, ct))
            return;

        bool useAvx = Avx2.IsSupported && Fma.IsSupported && Width >= 4;

        Parallel.For(0, Height, new ParallelOptions { CancellationToken = ct }, y =>
        {
            if (ct.IsCancellationRequested) return;
            double dy = (y - Height * 0.5) * scale;
            double ciScalar = CenterY + dy;
            int rowBase = y * Width;
            int x = 0;
            if (useAvx)
            {
                var ciVec = Vector256.Create(ciScalar);
                for (; x + 4 <= Width; x += 4)
                {
                    double cx0 = CenterX + (x     - Width * 0.5) * scale;
                    double cx1 = CenterX + (x + 1 - Width * 0.5) * scale;
                    double cx2 = CenterX + (x + 2 - Width * 0.5) * scale;
                    double cx3 = CenterX + (x + 3 - Width * 0.5) * scale;
                    var crVec = Vector256.Create(cx0, cx1, cx2, cx3);
                    IterateLaneAvx2(crVec, ciVec, ColorBuffer, rowBase + x);
                }
            }
            for (; x < Width; x++)
            {
                double cx = CenterX + (x - Width * 0.5) * scale;
                IteratePixelScalar(cx, ciScalar, ColorBuffer, rowBase + x);
            }
        });
    }

    // ── Scalar (reference) path ─────────────────────────────────────────────

    private void IteratePixelScalar(double cr, double ci, uint[] buf, int idx)
    {
        double zr = 0.0, zi = 0.0;
        double dr = 0.0, di = 0.0;
        int it = 0;
        int maxIt = MaxIterations;
        for (; it < maxIt; it++)
        {
            double r2 = zr * zr + zi * zi;
            if (r2 >= Bailout2) break;
            double dr_new = (((((zr + zr) * zr - (zi + zi) * zi) + (zr * zr - zi * zi)) * dr - (((zr + zr) * zi + (zi + zi) * zr) + (zr * zi + zi * zr)) * di) + 1.0);
            double di_new = ((((zr + zr) * zr - (zi + zi) * zi) + (zr * zr - zi * zi)) * di + (((zr + zr) * zi + (zi + zi) * zr) + (zr * zi + zi * zr)) * dr);
            double zr_new = (((zr * zr - zi * zi) * zr - (zr * zi + zi * zr) * zi) + cr);
            double zi_new = (((zr * zr - zi * zi) * zi + (zr * zi + zi * zr) * zr) + ci);
            zr = zr_new; zi = zi_new;
            dr = dr_new; di = di_new;
        }
        buf[idx] = ColorFor(it, zr, zi, dr, di, maxIt);
    }

    // Iteration-count-only variant (no colour writeback). Used by the
    // self-test to compare the AVX2 path against the scalar reference.
    internal int IteratePixelScalarRaw(double cr, double ci,
                                       out double zrOut, out double ziOut,
                                       out double drOut, out double diOut)
    {
        double zr = 0.0, zi = 0.0;
        double dr = 0.0, di = 0.0;
        int it = 0;
        int maxIt = MaxIterations;
        for (; it < maxIt; it++)
        {
            double r2 = zr * zr + zi * zi;
            if (r2 >= Bailout2) break;
            double dr_new = (((((zr + zr) * zr - (zi + zi) * zi) + (zr * zr - zi * zi)) * dr - (((zr + zr) * zi + (zi + zi) * zr) + (zr * zi + zi * zr)) * di) + 1.0);
            double di_new = ((((zr + zr) * zr - (zi + zi) * zi) + (zr * zr - zi * zi)) * di + (((zr + zr) * zi + (zi + zi) * zr) + (zr * zi + zi * zr)) * dr);
            double zr_new = (((zr * zr - zi * zi) * zr - (zr * zi + zi * zr) * zi) + cr);
            double zi_new = (((zr * zr - zi * zi) * zi + (zr * zi + zi * zr) * zr) + ci);
            zr = zr_new; zi = zi_new;
            dr = dr_new; di = di_new;
        }
        zrOut = zr; ziOut = zi; drOut = dr; diOut = di;
        return it;
    }

    // ── AVX2 path (4 pixels per lane) ───────────────────────────────────────

    private void IterateLaneAvx2(Vector256<double> cr, Vector256<double> ci, uint[] buf, int idx)
    {
        Vector256<double> zr = Vector256<double>.Zero;
        Vector256<double> zi = Vector256<double>.Zero;
        Vector256<double> dr = Vector256<double>.Zero;
        Vector256<double> di = Vector256<double>.Zero;
        Vector256<double> bailoutVec = Vector256.Create(Bailout2);
        Vector256<long> itCounts = Vector256<long>.Zero;
        Vector256<long> oneL = Vector256.Create(1L);
        Vector256<long> activeLanes = Vector256.Create(-1L);   // all lanes active initially

        int maxIt = MaxIterations;
        for (int n = 0; n < maxIt; n++)
        {
            var r2 = Fma.MultiplyAdd(zr, zr, Avx.Multiply(zi, zi));
            // active = (r2 < bailout) — lanes that have NOT yet escaped
            var activeMaskD = Avx.Compare(r2, bailoutVec, FloatComparisonMode.OrderedLessThanNonSignaling);
            var activeMaskL = activeMaskD.AsInt64();
            activeLanes = Avx2.And(activeLanes, activeMaskL);
            if (Avx.MoveMask(activeMaskD) == 0) break;
            itCounts = Avx2.Add(itCounts, Avx2.And(oneL, activeMaskL));

                Vector256<double> d_re1 = Avx.Add(zr, zr);
                Vector256<double> d_im2 = Avx.Add(zi, zi);
                Vector256<double> d_re3 = Fma.MultiplyAddNegated(d_im2, zi, Avx.Multiply(d_re1, zr));
                Vector256<double> d_im4 = Fma.MultiplyAdd(d_re1, zi, Avx.Multiply(d_im2, zr));
                Vector256<double> d_re5 = Fma.MultiplyAddNegated(zi, zi, Avx.Multiply(zr, zr));
                Vector256<double> d_im6 = Fma.MultiplyAdd(zr, zi, Avx.Multiply(zi, zr));
                Vector256<double> d_re7 = Avx.Add(d_re3, d_re5);
                Vector256<double> d_im8 = Avx.Add(d_im4, d_im6);
                Vector256<double> d_re9 = Fma.MultiplyAddNegated(d_im8, di, Avx.Multiply(d_re7, dr));
                Vector256<double> d_im10 = Fma.MultiplyAdd(d_re7, di, Avx.Multiply(d_im8, dr));
                Vector256<double> d_re11 = Vector256.Create(1.0);
                Vector256<double> d_re12 = Avx.Add(d_re9, d_re11);
                Vector256<double> dr_new = d_re12;
                Vector256<double> di_new = d_im10;
                Vector256<double> z_re1 = Fma.MultiplyAddNegated(zi, zi, Avx.Multiply(zr, zr));
                Vector256<double> z_im2 = Fma.MultiplyAdd(zr, zi, Avx.Multiply(zi, zr));
                Vector256<double> z_re3 = Fma.MultiplyAddNegated(z_im2, zi, Avx.Multiply(z_re1, zr));
                Vector256<double> z_im4 = Fma.MultiplyAdd(z_re1, zi, Avx.Multiply(z_im2, zr));
                Vector256<double> z_re5 = Avx.Add(z_re3, cr);
                Vector256<double> z_im6 = Avx.Add(z_im4, ci);
                Vector256<double> zr_new = z_re5;
                Vector256<double> zi_new = z_im6;

            // Freeze z, dz/dc for any lane that escaped this iteration; live
            // lanes pick up the new values.
            var keepD = activeMaskL.AsDouble();
            zr = Avx.BlendVariable(zr, zr_new, keepD);
            zi = Avx.BlendVariable(zi, zi_new, keepD);
            dr = Avx.BlendVariable(dr, dr_new, keepD);
            di = Avx.BlendVariable(di, di_new, keepD);
        }

        Span<long> its = stackalloc long[4];
        Span<double> zrs = stackalloc double[4];
        Span<double> zis = stackalloc double[4];
        Span<double> drs = stackalloc double[4];
        Span<double> dis = stackalloc double[4];
        itCounts.CopyTo(its);
        zr.CopyTo(zrs); zi.CopyTo(zis);
        dr.CopyTo(drs); di.CopyTo(dis);
        for (int k = 0; k < 4; k++)
            buf[idx + k] = ColorFor((int)its[k], zrs[k], zis[k], drs[k], dis[k], MaxIterations);
    }

    // Iteration-count-only variant for the self-test (no colour writeback).
    internal void IterateLaneAvx2Raw(Vector256<double> cr, Vector256<double> ci,
                                      Span<int> outIters)
    {
        Vector256<double> zr = Vector256<double>.Zero;
        Vector256<double> zi = Vector256<double>.Zero;
        Vector256<double> dr = Vector256<double>.Zero;
        Vector256<double> di = Vector256<double>.Zero;
        Vector256<double> bailoutVec = Vector256.Create(Bailout2);
        Vector256<long> itCounts = Vector256<long>.Zero;
        Vector256<long> oneL = Vector256.Create(1L);

        int maxIt = MaxIterations;
        for (int n = 0; n < maxIt; n++)
        {
            var r2 = Fma.MultiplyAdd(zr, zr, Avx.Multiply(zi, zi));
            var activeMaskD = Avx.Compare(r2, bailoutVec, FloatComparisonMode.OrderedLessThanNonSignaling);
            var activeMaskL = activeMaskD.AsInt64();
            if (Avx.MoveMask(activeMaskD) == 0) break;
            itCounts = Avx2.Add(itCounts, Avx2.And(oneL, activeMaskL));

                Vector256<double> d_re1 = Avx.Add(zr, zr);
                Vector256<double> d_im2 = Avx.Add(zi, zi);
                Vector256<double> d_re3 = Fma.MultiplyAddNegated(d_im2, zi, Avx.Multiply(d_re1, zr));
                Vector256<double> d_im4 = Fma.MultiplyAdd(d_re1, zi, Avx.Multiply(d_im2, zr));
                Vector256<double> d_re5 = Fma.MultiplyAddNegated(zi, zi, Avx.Multiply(zr, zr));
                Vector256<double> d_im6 = Fma.MultiplyAdd(zr, zi, Avx.Multiply(zi, zr));
                Vector256<double> d_re7 = Avx.Add(d_re3, d_re5);
                Vector256<double> d_im8 = Avx.Add(d_im4, d_im6);
                Vector256<double> d_re9 = Fma.MultiplyAddNegated(d_im8, di, Avx.Multiply(d_re7, dr));
                Vector256<double> d_im10 = Fma.MultiplyAdd(d_re7, di, Avx.Multiply(d_im8, dr));
                Vector256<double> d_re11 = Vector256.Create(1.0);
                Vector256<double> d_re12 = Avx.Add(d_re9, d_re11);
                Vector256<double> dr_new = d_re12;
                Vector256<double> di_new = d_im10;
                Vector256<double> z_re1 = Fma.MultiplyAddNegated(zi, zi, Avx.Multiply(zr, zr));
                Vector256<double> z_im2 = Fma.MultiplyAdd(zr, zi, Avx.Multiply(zi, zr));
                Vector256<double> z_re3 = Fma.MultiplyAddNegated(z_im2, zi, Avx.Multiply(z_re1, zr));
                Vector256<double> z_im4 = Fma.MultiplyAdd(z_re1, zi, Avx.Multiply(z_im2, zr));
                Vector256<double> z_re5 = Avx.Add(z_re3, cr);
                Vector256<double> z_im6 = Avx.Add(z_im4, ci);
                Vector256<double> zr_new = z_re5;
                Vector256<double> zi_new = z_im6;

            var keepD = activeMaskL.AsDouble();
            zr = Avx.BlendVariable(zr, zr_new, keepD);
            zi = Avx.BlendVariable(zi, zi_new, keepD);
            dr = Avx.BlendVariable(dr, dr_new, keepD);
            di = Avx.BlendVariable(di, di_new, keepD);
        }

        Span<long> its = stackalloc long[4];
        itCounts.CopyTo(its);
        for (int k = 0; k < 4; k++) outIters[k] = (int)its[k];
    }

    // ── ILGPU path (Tier 6) ─────────────────────────────────────────────────
    //
    // Generated kernel: one work item per pixel. Iterates in plain
    // scalar `double` (same body as the CPU scalar path, no SIMD) and
    // writes a RawPixel struct. CPU post-pass runs IColorMap.Map across
    // the buffer in parallel so the theme system remains live.

    public struct GpuParams
    {
        public int Width;
        public int Height;
        public double CenterX;
        public double CenterY;
        public double Scale;
        public int MaxIter;
        public double Bailout2;
    }

    public struct RawPixel
    {
        public int Iter;
        public double Zr;
        public double Zi;
        public double Dr;
        public double Di;
    }

    private Context? _gpuContext;
    private Accelerator? _gpuAccel;
    private Action<Index1D, ArrayView<RawPixel>, GpuParams>? _gpuKernel;
    private bool _gpuInitFailed;
    public string LastGpuError { get; private set; } = string.Empty;

    private bool TryInitGpu()
    {
        if (_gpuKernel != null) return true;
        if (_gpuInitFailed) return false;
        try
        {
            _gpuContext = Context.Create(b => b.Default());
            _gpuAccel   = _gpuContext.GetPreferredDevice(preferCPU: false).CreateAccelerator(_gpuContext);
            _gpuKernel  = _gpuAccel.LoadAutoGroupedStreamKernel<Index1D, ArrayView<RawPixel>, GpuParams>(Kernel);
            return true;
        }
        catch (Exception ex)
        {
            LastGpuError = ex.Message;
            _gpuInitFailed = true;
            return false;
        }
    }

    private bool TryRenderGpu(double scale, CancellationToken ct)
    {
        if (!TryInitGpu() || _gpuAccel == null || _gpuKernel == null) return false;
        try
        {
            int total = Width * Height;
            using var dev = _gpuAccel.Allocate1D<RawPixel>(total);
            var p = new GpuParams
            {
                Width    = Width,
                Height   = Height,
                CenterX  = CenterX,
                CenterY  = CenterY,
                Scale    = scale,
                MaxIter  = MaxIterations,
                Bailout2 = Bailout2,
            };
            _gpuKernel(total, dev.View, p);
            _gpuAccel.Synchronize();
            if (ct.IsCancellationRequested) return false;
            var raw = new RawPixel[total];
            dev.CopyToCPU(raw);
            Parallel.For(0, total, new ParallelOptions { CancellationToken = ct }, i =>
            {
                if (ct.IsCancellationRequested) return;
                var rp = raw[i];
                ColorBuffer[i] = ColorFor(rp.Iter, rp.Zr, rp.Zi, rp.Dr, rp.Di, MaxIterations);
            });
            return true;
        }
        catch (Exception ex)
        {
            LastGpuError = ex.Message;
            return false;
        }
    }

    private static void Kernel(Index1D idx, ArrayView<RawPixel> output, GpuParams p)
    {
        int x = idx % p.Width;
        int y = idx / p.Width;
        if (y >= p.Height) return;
        double cr = p.CenterX + (x - p.Width  * 0.5) * p.Scale;
        double ci = p.CenterY + (y - p.Height * 0.5) * p.Scale;
        double zr = 0.0, zi = 0.0;
        double dr = 0.0, di = 0.0;
        int it = 0;
        int maxIt = p.MaxIter;
        for (; it < maxIt; it++)
        {
            double r2 = zr * zr + zi * zi;
            if (r2 >= p.Bailout2) break;
            double dr_new = (((((zr + zr) * zr - (zi + zi) * zi) + (zr * zr - zi * zi)) * dr - (((zr + zr) * zi + (zi + zi) * zr) + (zr * zi + zi * zr)) * di) + 1.0);
            double di_new = ((((zr + zr) * zr - (zi + zi) * zi) + (zr * zr - zi * zi)) * di + (((zr + zr) * zi + (zi + zi) * zr) + (zr * zi + zi * zr)) * dr);
            double zr_new = (((zr * zr - zi * zi) * zr - (zr * zi + zi * zr) * zi) + cr);
            double zi_new = (((zr * zr - zi * zi) * zi + (zr * zi + zi * zr) * zr) + ci);
            zr = zr_new; zi = zi_new;
            dr = dr_new; di = di_new;
        }
        RawPixel rp;
        rp.Iter = it;
        rp.Zr = zr; rp.Zi = zi;
        rp.Dr = dr; rp.Di = di;
        output[idx] = rp;
    }

    public void Dispose()
    {
        _gpuAccel?.Dispose(); _gpuAccel = null;
        _gpuContext?.Dispose(); _gpuContext = null;
        _gpuKernel = null;
    }

    // ── Perturbation path (Tier 4) ──────────────────────────────────────────
    //
    // Reference orbit at the view centre (plain double precision), then a
    // per-pixel δ iteration using the symbolic expansion of
    //
    //     δ_{n+1}  =  p(Z+δ, C+ε)  −  p(Z, C)
    //                 =  ε + ((z + z)*z + z*z)*δ + 0.5*(2*z + z + z + z + z)*δ*δ + δ*δ*δ
    //
    // For polynomial step functions the expansion is exact — no
    // truncation error beyond the round-off of the reference orbit's
    // doubles. Falls back to the AVX2 path (returns false) when the
    // reference orbit escapes before maxIter (rare; happens when the
    // view centre itself lies outside the set).

    private bool TryRenderPerturbation(double scale, CancellationToken ct)
    {
        int maxIt = MaxIterations;
        // Reference orbit at view centre C = (CenterX, CenterY).
        double Cr = CenterX, Ci = CenterY;
        var refZr = new double[maxIt + 1];
        var refZi = new double[maxIt + 1];
        {
            double zr = 0.0, zi = 0.0;
            int n;
            for (n = 0; n < maxIt; n++)
            {
                double r2 = zr * zr + zi * zi;
                if (r2 >= Bailout2) return false;   // reference escaped; bail to CPU
                refZr[n] = zr;
                refZi[n] = zi;
                // Reuse the scalar z-update body (no derivative needed for ref orbit).
                double cr = Cr, ci = Ci;
                double dr = 0.0, di = 0.0;          // unused; kept so SCALAR_Z_BODY parses
            double zr_new = (((zr * zr - zi * zi) * zr - (zr * zi + zi * zr) * zi) + cr);
            double zi_new = (((zr * zr - zi * zi) * zi + (zr * zi + zi * zr) * zr) + ci);
                zr = zr_new; zi = zi_new;
            }
            refZr[maxIt] = zr; refZi[maxIt] = zi;
        }

        Parallel.For(0, Height, new ParallelOptions { CancellationToken = ct }, y =>
        {
            if (ct.IsCancellationRequested) return;
            double cy = CenterY + (y - Height * 0.5) * scale;
            double ei = cy - Ci;
            int rowBase = y * Width;
            for (int x = 0; x < Width; x++)
            {
                double cx = CenterX + (x - Width * 0.5) * scale;
                double er = cx - Cr;
                double dr = 0.0, di = 0.0;     // δ
                int it = 0;
                int finalIt = maxIt;
                double finalZr = 0.0, finalZi = 0.0;
                for (; it < maxIt; it++)
                {
                    double Zr = refZr[it], Zi = refZi[it];
                    double zr = Zr + dr, zi = Zi + di;
                    double r2 = zr * zr + zi * zi;
                    if (r2 >= Bailout2) { finalIt = it; finalZr = zr; finalZi = zi; goto done; }
                    double dr_new = (((er + ((((Zr + Zr) * Zr - (Zi + Zi) * Zi) + (Zr * Zr - Zi * Zi)) * dr - (((Zr + Zr) * Zi + (Zi + Zi) * Zr) + (Zr * Zi + Zi * Zr)) * di)) + (((0.5 * (((2.0 * Zr) + (Zr + Zr)) + (Zr + Zr))) * dr - (0.5 * (((2.0 * Zi) + (Zi + Zi)) + (Zi + Zi))) * di) * dr - ((0.5 * (((2.0 * Zr) + (Zr + Zr)) + (Zr + Zr))) * di + (0.5 * (((2.0 * Zi) + (Zi + Zi)) + (Zi + Zi))) * dr) * di)) + ((dr * dr - di * di) * dr - (dr * di + di * dr) * di));
                    double di_new = (((ei + ((((Zr + Zr) * Zr - (Zi + Zi) * Zi) + (Zr * Zr - Zi * Zi)) * di + (((Zr + Zr) * Zi + (Zi + Zi) * Zr) + (Zr * Zi + Zi * Zr)) * dr)) + (((0.5 * (((2.0 * Zr) + (Zr + Zr)) + (Zr + Zr))) * dr - (0.5 * (((2.0 * Zi) + (Zi + Zi)) + (Zi + Zi))) * di) * di + ((0.5 * (((2.0 * Zr) + (Zr + Zr)) + (Zr + Zr))) * di + (0.5 * (((2.0 * Zi) + (Zi + Zi)) + (Zi + Zi))) * dr) * dr)) + ((dr * dr - di * di) * di + (dr * di + di * dr) * dr));
                    dr = dr_new; di = di_new;
                }
                {
                    double Zr = refZr[maxIt], Zi = refZi[maxIt];
                    finalZr = Zr + dr; finalZi = Zi + di;
                }
                done:
                ColorBuffer[rowBase + x] = ColorFor(finalIt, finalZr, finalZi, 0.0, 0.0, maxIt);
            }
        });
        return true;
    }

    // ── Colour mapping ──────────────────────────────────────────────────────
    //
    // Uses the nine-parameter IColorMap.Map overload so themes get smooth
    // count, distance estimate, normal direction, final z, and final dz/dc.
    // Themes that ignore these inherit the default 3-arg fallback via the
    // interface's default implementations.

    private uint ColorFor(int it, double zr, double zi, double dr, double di, int maxIt)
    {
        if (it >= maxIt) return ColorMap.InSetColor;

        double zMag2 = zr * zr + zi * zi;
        double zMag  = Math.Sqrt(zMag2);
        double dMag2 = dr * dr + di * di;
        double dMag  = Math.Sqrt(dMag2);

        // Smooth iteration count: standard log-log normalisation.
        float smooth = (float)(it + 1.0
            - Math.Log2(Math.Max(1e-10, Math.Log2(Math.Max(zMag, 1.0 + 1e-10)))));

        // Surface normal (Inigo Quilez): u + v·i  ∝  z · conj(dz/dc)
        //   u = zr·dr + zi·di
        //   v = zi·dr − zr·di
        double u = zr * dr + zi * di;
        double v = zi * dr - zr * di;
        double m = Math.Sqrt(u * u + v * v);
        float nx = 0f, ny = 0f;
        if (m > 1e-30) { nx = (float)(u / m); ny = (float)(v / m); }

        // Exterior distance estimate (Milnor / Hubbard):
        //   d ≈ 0.5 · |z| · log|z| / |dz/dc|
        // Returned in complex-plane units; themes scale by _lastPixelScale.
        float distance = 0f;
        if (dMag > 1e-30 && zMag > 1.0)
            distance = (float)(0.5 * zMag * Math.Log(zMag) / dMag);

        return (uint)ColorMap.Map(
            smooth, distance, maxIt, nx, ny,
            (float)zr, (float)zi, (float)dr, (float)di);
    }
}
