// {{CLASS_NAME}}.cs — GENERATED by CalculatorGen
//
// Source equation (z, c complex):
//     z_{n+1} = {{EQUATION_SOURCE}}
//
// Symbolic derivatives (auto-derived):
//     ∂p/∂z = {{DPDZ_TEXT}}
//     ∂p/∂c = {{DPDC_TEXT}}
//
// Per-iteration derivative recurrence (used for Inigo Quilez surface
// normals and the exterior distance estimate):
//
//     dz_{n+1}/dc  =  (∂p/∂z) · (dz_n/dc)  +  (∂p/∂c)
//                  =  {{DERIV_TEXT}}
//
// Generator: CalculatorGen v0.3 (polynomial + symbolic diff + ILGPU)
// Generated: {{TIMESTAMP}}
//
// DO NOT HAND-EDIT. Re-run CalculatorGen with the same --name flag to
// regenerate. If you need behaviour the generator cannot produce
// (transcendentals, abs-fold, conditional branches), copy this file,
// rename the class, and remove this banner.
//
// Implementation notes
// ──────────────────────────────────────────────────────────────────────
//   • Scalar path: portable double-precision, one pixel at a time. Used
//     as the correctness reference and as the fallback when AVX2+FMA is
//     unavailable.
//   • AVX2 path:  Vector256<double> (4 pixels per lane). Complex multiply
//     uses Fma.MultiplyAdd / MultiplyAddNegated pairs.
//   • GPU path (Tier 6): ILGPU-compiled kernel issues one work item per
//     pixel. Returns a raw-state buffer (iter + z + dz/dc); the CPU
//     post-pass runs IColorMap.Map across the buffer in parallel, so the
//     theme system is fully honoured. Opt-in via UseGpu = true; lazy
//     accelerator init, falls back to AVX2/scalar on failure.
//   • Perturbation path (Tier 4): reference-orbit double-precision walk
//     plus a δ-iteration kernel built from the symbolic Taylor expansion
//     of p(Z+δ, c+ε) − p(Z, c). Used by the deep-zoom theme when the
//     view's Zoom > _perturbThreshold. Symbolically exact for polynomial
//     equations — no truncation error beyond round-off in the reference
//     orbit's doubles.
//   • BLA tables (Tier 5): per-iteration Bilinear Approximation
//     A_n = ∂p/∂z(Z_n), B_n = ∂p/∂c(Z_n). Active iterations are skipped
//     in bulk when the linearisation is valid.
//   • Derivative tracking: dz/dc is updated alongside z every iteration.
//     At escape it feeds two colour-map inputs:
//       - nx, ny = unit normal to the escape-potential level curve
//                  (Inigo Quilez:  z · conj(dz/dc), normalised)
//       - distance = exterior distance estimate
//                    (Milnor / Hubbard:  0.5 · |z| · log|z| / |dz/dc|)
//   • Raw helpers (IteratePixelScalarRaw / IterateLaneAvx2Raw) expose
//     iteration counts without colour; used by {{CLASS_NAME}}SelfTest
//     to validate scalar ↔ AVX2 agreement.

using System;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using System.Threading;
using System.Threading.Tasks;

using ILGPU;
using ILGPU.Runtime;

using FracturingFog.FFMath;
using FracturingFog.Interefaces;
using FracturingFog.Models;

namespace FracturingFog.Calculators.Generated;

public sealed class {{CLASS_NAME}} : IFractalCalculator, IDisposable
{
    public int Width  { get; private set; }
    public int Height { get; private set; }
    public uint[] ColorBuffer { get; private set; } = Array.Empty<uint>();

    public double CenterX { get; set; } = 0.0;
    public double CenterY { get; set; } = 0.0;
    public double Zoom    { get; set; } = 1.0;
    public int MaxIterations { get; set; } = 512;

    // ── Extended-precision centre limbs (Big+) ──────────────────────────────
    //
    // The IFractalCalculator contract carries only a double-precision centre,
    // which limits naïve scalar/AVX2 to about zoom 1e13. The legacy
    // MandelbrotCalculator carries four limbs (Hi, Lo, X2, X3) that compose
    // into a QuadDouble; the renderer plumbs them via these properties when
    // present so the perturbation reference orbit can iterate at ~62-digit
    // precision (~1e50 zoom ceiling).
    //
    // Defaults zero so callers that only set Hi behave like double centres.
    public double CenterXLo { get; set; }
    public double CenterX2  { get; set; }
    public double CenterX3  { get; set; }
    public double CenterYLo { get; set; }
    public double CenterY2  { get; set; }
    public double CenterY3  { get; set; }

    /// <summary>Threshold beyond which the perturbation path switches its
    /// reference orbit from plain double to QuadDouble. Defaults to 1e12 —
    /// double precision starts losing accuracy in the iterate around zoom
    /// 1e13, so the switch lands one decade earlier for headroom.</summary>
    public double ExtendedRefZoomThreshold { get; set; } = 1.0e12;

    public QualityPreset Quality { get; set; } = QualityPreset.Standard;
    public IColorMap ColorMap { get; set; } = new HsvPalette();

    public bool SupportsZoomPan => true;

    /// <summary>Label describing which precision path ran on the last
    /// Calculate() call: "SP" (double-only), "DD" (DoubleDouble δ), or
    /// "QD" (QuadDouble reference orbit + DD δ). Surfaced by the render
    /// host into the status bar so callers can verify the deep-zoom
    /// fallback engaged.</summary>
    public string LastPrecisionLabel { get; private set; } = "SP";

    /// <summary>Opt-in GPU execution. When true, Calculate dispatches to an
    /// ILGPU kernel and falls back to AVX2 if the device is unavailable or
    /// the kernel fails to load.</summary>
    public bool UseGpu { get; set; } = false;

    /// <summary>Opt-in perturbation deep-zoom path. When true and Zoom exceeds
    /// PerturbZoomThreshold, the renderer computes a reference orbit + per-
    /// pixel δ iteration instead of full double-precision iteration. Tier 4.</summary>
    public bool UsePerturbation { get; set; } = false;
    public double PerturbZoomThreshold { get; set; } = 1.0e12;

    /// <summary>Opt-in BLA acceleration (Tier 5). Requires UsePerturbation.</summary>
    public bool UseBla { get; set; } = false;

    /// <summary>Threshold beyond which the per-pixel δ loop switches from
    /// plain double to DoubleDouble. At zoom ~1e12 the per-pixel ε is
    /// already at the ULP of double, so adding it to δ once δ has grown
    /// larger than ε truncates the per-pixel signal — adjacent pixels lock
    /// onto the same iteration count, producing visible pixelation. DD
    /// gives ~31 digits, enough to keep the δ recurrence accurate through
    /// the QD reference orbit's range (~1e50). Defaults to 1e12.</summary>
    public double DdDeltaZoomThreshold { get; set; } = 1.0e12;

    /// <summary>Threshold for the HP-direct per-pixel fallback (used when
    /// perturbation can't track the orbit). Below this zoom the fallback
    /// runs in DD (~31 digits); above it, QD (~62 digits). Matches the
    /// legacy MandelbrotCalculator's QDZoomThreshold. Defaults to 1e25.</summary>
    public double QdDirectZoomThreshold { get; set; } = 1.0e25;

    // Bailout radius². Generous default; tighten if the equation has a
    // smaller natural escape boundary.
    private const double Bailout2 = 1024.0;

    private double _lastPixelScale = 1.0;

    public {{CLASS_NAME}}(int width, int height) => Resize(width, height);

    public void Resize(int width, int height)
    {
        Width  = width;
        Height = height;
        ColorBuffer = new uint[width * height];
    }

    public void Calculate(CancellationToken ct = default)
    {
        ColorMap.MaxIterations = MaxIterations;
        double scale = (3.5 / Math.Max(Width, Height)) / Zoom;
        _lastPixelScale = scale;
        LastPrecisionLabel = "SP";

        // GPU path: opt-in, lazy init, automatic fallback.
        if (UseGpu && TryRenderGpu(scale, ct)) { LastPrecisionLabel = "GPU"; return; }

        // Perturbation is the deep-zoom workhorse — DD/QD reference orbit
        // computed ONCE for the frame, then double-precision δ per pixel
        // (cheap). Per-pixel glitch detection inside the loop falls back
        // to HP-direct for individual misbehaving pixels, so the slow path
        // only pays for the small fraction of pixels that need it. When
        // the reference orbit itself escapes (centre is outside the set
        // at deep zoom) TryRenderPerturbation returns false and the
        // whole-frame HP-direct fallback below takes over.
        if (UsePerturbation && Zoom >= PerturbZoomThreshold && TryRenderPerturbation(scale, ct))
            return;

        // Whole-frame HP-direct fallback (reference orbit escaped, or the
        // user opted out of perturbation at deep zoom). Slow — DD/QD per
        // pixel from iter 0 — but correct at any zoom DD/QD can represent.
        if (Zoom >= DdDeltaZoomThreshold)
        {
            TryRenderHpDirect(scale, ct);
            return;
        }

        bool useAvx = Avx2.IsSupported && Fma.IsSupported && Width >= 4;

        Parallel.For(0, Height, new ParallelOptions { CancellationToken = ct }, y =>
        {
            if (ct.IsCancellationRequested) return;
            double dy = (y - Height * 0.5) * scale;
            double ciScalar = CenterY + dy;
            int rowBase = y * Width;
            int x = 0;
            if (useAvx)
            {
                var ciVec = Vector256.Create(ciScalar);
                for (; x + 4 <= Width; x += 4)
                {
                    double cx0 = CenterX + (x     - Width * 0.5) * scale;
                    double cx1 = CenterX + (x + 1 - Width * 0.5) * scale;
                    double cx2 = CenterX + (x + 2 - Width * 0.5) * scale;
                    double cx3 = CenterX + (x + 3 - Width * 0.5) * scale;
                    var crVec = Vector256.Create(cx0, cx1, cx2, cx3);
                    IterateLaneAvx2(crVec, ciVec, ColorBuffer, rowBase + x);
                }
            }
            for (; x < Width; x++)
            {
                double cx = CenterX + (x - Width * 0.5) * scale;
                IteratePixelScalar(cx, ciScalar, ColorBuffer, rowBase + x);
            }
        });
    }

    // ── Scalar (reference) path ─────────────────────────────────────────────

    private void IteratePixelScalar(double cr, double ci, uint[] buf, int idx)
    {
        double zr = 0.0, zi = 0.0;
        double dr = 0.0, di = 0.0;
        int it = 0;
        int maxIt = MaxIterations;
        for (; it < maxIt; it++)
        {
            double r2 = zr * zr + zi * zi;
            if (r2 >= Bailout2) break;
{{SCALAR_D_BODY}}
{{SCALAR_Z_BODY}}
            zr = zr_new; zi = zi_new;
            dr = dr_new; di = di_new;
        }
        buf[idx] = ColorFor(it, zr, zi, dr, di, maxIt);
    }

    // Iteration-count-only variant (no colour writeback). Used by the
    // self-test to compare the AVX2 path against the scalar reference.
    internal int IteratePixelScalarRaw(double cr, double ci,
                                       out double zrOut, out double ziOut,
                                       out double drOut, out double diOut)
    {
        double zr = 0.0, zi = 0.0;
        double dr = 0.0, di = 0.0;
        int it = 0;
        int maxIt = MaxIterations;
        for (; it < maxIt; it++)
        {
            double r2 = zr * zr + zi * zi;
            if (r2 >= Bailout2) break;
{{SCALAR_D_BODY}}
{{SCALAR_Z_BODY}}
            zr = zr_new; zi = zi_new;
            dr = dr_new; di = di_new;
        }
        zrOut = zr; ziOut = zi; drOut = dr; diOut = di;
        return it;
    }

    // ── AVX2 path (4 pixels per lane) ───────────────────────────────────────

    private void IterateLaneAvx2(Vector256<double> cr, Vector256<double> ci, uint[] buf, int idx)
    {
        Vector256<double> zr = Vector256<double>.Zero;
        Vector256<double> zi = Vector256<double>.Zero;
        Vector256<double> dr = Vector256<double>.Zero;
        Vector256<double> di = Vector256<double>.Zero;
        Vector256<double> bailoutVec = Vector256.Create(Bailout2);
        Vector256<long> itCounts = Vector256<long>.Zero;
        Vector256<long> oneL = Vector256.Create(1L);
        Vector256<long> activeLanes = Vector256.Create(-1L);   // all lanes active initially

        int maxIt = MaxIterations;
        for (int n = 0; n < maxIt; n++)
        {
            var r2 = Fma.MultiplyAdd(zr, zr, Avx.Multiply(zi, zi));
            // active = (r2 < bailout) — lanes that have NOT yet escaped
            var activeMaskD = Avx.Compare(r2, bailoutVec, FloatComparisonMode.OrderedLessThanNonSignaling);
            var activeMaskL = activeMaskD.AsInt64();
            activeLanes = Avx2.And(activeLanes, activeMaskL);
            if (Avx.MoveMask(activeMaskD) == 0) break;
            itCounts = Avx2.Add(itCounts, Avx2.And(oneL, activeMaskL));

{{AVX2_D_BODY}}
{{AVX2_Z_BODY}}

            // Freeze z, dz/dc for any lane that escaped this iteration; live
            // lanes pick up the new values.
            var keepD = activeMaskL.AsDouble();
            zr = Avx.BlendVariable(zr, zr_new, keepD);
            zi = Avx.BlendVariable(zi, zi_new, keepD);
            dr = Avx.BlendVariable(dr, dr_new, keepD);
            di = Avx.BlendVariable(di, di_new, keepD);
        }

        Span<long> its = stackalloc long[4];
        Span<double> zrs = stackalloc double[4];
        Span<double> zis = stackalloc double[4];
        Span<double> drs = stackalloc double[4];
        Span<double> dis = stackalloc double[4];
        itCounts.CopyTo(its);
        zr.CopyTo(zrs); zi.CopyTo(zis);
        dr.CopyTo(drs); di.CopyTo(dis);
        for (int k = 0; k < 4; k++)
            buf[idx + k] = ColorFor((int)its[k], zrs[k], zis[k], drs[k], dis[k], MaxIterations);
    }

    // Iteration-count-only variant for the self-test (no colour writeback).
    internal void IterateLaneAvx2Raw(Vector256<double> cr, Vector256<double> ci,
                                      Span<int> outIters)
    {
        Vector256<double> zr = Vector256<double>.Zero;
        Vector256<double> zi = Vector256<double>.Zero;
        Vector256<double> dr = Vector256<double>.Zero;
        Vector256<double> di = Vector256<double>.Zero;
        Vector256<double> bailoutVec = Vector256.Create(Bailout2);
        Vector256<long> itCounts = Vector256<long>.Zero;
        Vector256<long> oneL = Vector256.Create(1L);

        int maxIt = MaxIterations;
        for (int n = 0; n < maxIt; n++)
        {
            var r2 = Fma.MultiplyAdd(zr, zr, Avx.Multiply(zi, zi));
            var activeMaskD = Avx.Compare(r2, bailoutVec, FloatComparisonMode.OrderedLessThanNonSignaling);
            var activeMaskL = activeMaskD.AsInt64();
            if (Avx.MoveMask(activeMaskD) == 0) break;
            itCounts = Avx2.Add(itCounts, Avx2.And(oneL, activeMaskL));

{{AVX2_D_BODY}}
{{AVX2_Z_BODY}}

            var keepD = activeMaskL.AsDouble();
            zr = Avx.BlendVariable(zr, zr_new, keepD);
            zi = Avx.BlendVariable(zi, zi_new, keepD);
            dr = Avx.BlendVariable(dr, dr_new, keepD);
            di = Avx.BlendVariable(di, di_new, keepD);
        }

        Span<long> its = stackalloc long[4];
        itCounts.CopyTo(its);
        for (int k = 0; k < 4; k++) outIters[k] = (int)its[k];
    }

    // ── ILGPU path (Tier 6) ─────────────────────────────────────────────────
    //
    // Generated kernel: one work item per pixel. Iterates in plain
    // scalar `double` (same body as the CPU scalar path, no SIMD) and
    // writes a RawPixel struct. CPU post-pass runs IColorMap.Map across
    // the buffer in parallel so the theme system remains live.

    public struct GpuParams
    {
        public int Width;
        public int Height;
        public double CenterX;
        public double CenterY;
        public double Scale;
        public int MaxIter;
        public double Bailout2;
    }

    public struct RawPixel
    {
        public int Iter;
        public double Zr;
        public double Zi;
        public double Dr;
        public double Di;
    }

    private Context? _gpuContext;
    private Accelerator? _gpuAccel;
    private Action<Index1D, ArrayView<RawPixel>, GpuParams>? _gpuKernel;
    private bool _gpuInitFailed;
    public string LastGpuError { get; private set; } = string.Empty;

    private bool TryInitGpu()
    {
        if (_gpuKernel != null) return true;
        if (_gpuInitFailed) return false;
        try
        {
            _gpuContext = Context.Create(b => b.Default());
            _gpuAccel   = _gpuContext.GetPreferredDevice(preferCPU: false).CreateAccelerator(_gpuContext);
            _gpuKernel  = _gpuAccel.LoadAutoGroupedStreamKernel<Index1D, ArrayView<RawPixel>, GpuParams>(Kernel);
            return true;
        }
        catch (Exception ex)
        {
            LastGpuError = ex.Message;
            _gpuInitFailed = true;
            return false;
        }
    }

    private bool TryRenderGpu(double scale, CancellationToken ct)
    {
        if (!TryInitGpu() || _gpuAccel == null || _gpuKernel == null) return false;
        try
        {
            int total = Width * Height;
            using var dev = _gpuAccel.Allocate1D<RawPixel>(total);
            var p = new GpuParams
            {
                Width    = Width,
                Height   = Height,
                CenterX  = CenterX,
                CenterY  = CenterY,
                Scale    = scale,
                MaxIter  = MaxIterations,
                Bailout2 = Bailout2,
            };
            _gpuKernel(total, dev.View, p);
            _gpuAccel.Synchronize();
            if (ct.IsCancellationRequested) return false;
            var raw = new RawPixel[total];
            dev.CopyToCPU(raw);
            Parallel.For(0, total, new ParallelOptions { CancellationToken = ct }, i =>
            {
                if (ct.IsCancellationRequested) return;
                var rp = raw[i];
                ColorBuffer[i] = ColorFor(rp.Iter, rp.Zr, rp.Zi, rp.Dr, rp.Di, MaxIterations);
            });
            return true;
        }
        catch (Exception ex)
        {
            LastGpuError = ex.Message;
            return false;
        }
    }

    private static void Kernel(Index1D idx, ArrayView<RawPixel> output, GpuParams p)
    {
        int x = idx % p.Width;
        int y = idx / p.Width;
        if (y >= p.Height) return;
        double cr = p.CenterX + (x - p.Width  * 0.5) * p.Scale;
        double ci = p.CenterY + (y - p.Height * 0.5) * p.Scale;
        double zr = 0.0, zi = 0.0;
        double dr = 0.0, di = 0.0;
        int it = 0;
        int maxIt = p.MaxIter;
        for (; it < maxIt; it++)
        {
            double r2 = zr * zr + zi * zi;
            if (r2 >= p.Bailout2) break;
{{SCALAR_D_BODY}}
{{SCALAR_Z_BODY}}
            zr = zr_new; zi = zi_new;
            dr = dr_new; di = di_new;
        }
        RawPixel rp;
        rp.Iter = it;
        rp.Zr = zr; rp.Zi = zi;
        rp.Dr = dr; rp.Di = di;
        output[idx] = rp;
    }

    public void Dispose()
    {
        _gpuAccel?.Dispose(); _gpuAccel = null;
        _gpuContext?.Dispose(); _gpuContext = null;
        _gpuKernel = null;
    }

    // ── Perturbation path (Tier 4) ──────────────────────────────────────────
    //
    // Reference orbit at the view centre (plain double precision), then a
    // per-pixel δ iteration using the symbolic expansion of
    //
    //     δ_{n+1}  =  p(Z+δ, C+ε)  −  p(Z, C)
    //                 =  {{PERTURB_DELTA_TEXT}}
    //
    // For polynomial step functions the expansion is exact — no
    // truncation error beyond the round-off of the reference orbit's
    // doubles. Falls back to the AVX2 path (returns false) when the
    // reference orbit escapes before maxIter (rare; happens when the
    // view centre itself lies outside the set).

    private bool TryRenderPerturbation(double scale, CancellationToken ct)
    {
        int maxIt = MaxIterations;
        // Reference-orbit centre. Use QD if the caller plumbed limbs and
        // we're zoomed deep enough that double would round-trip away. The
        // emitted scalar centre `(Cr, Ci)` is then `(double)Cqd` so the
        // δ-update path sees a centre consistent with the QD orbit's
        // high limb.
        // QD reference orbit triggers at the extended-ref zoom threshold —
        // the iteration math runs in QD even when the caller plumbed only
        // a double-precision centre (the lower limbs are zero, but the
        // ITERATE accumulates without losing ULPs from one step to the
        // next, which is what matters at deep zoom). This used to require
        // non-zero limbs to engage; that gated the QD path behind a
        // controller round-trip that doesn't happen when the user just
        // crosses the threshold from below.
        bool useExtendedRef = Zoom >= ExtendedRefZoomThreshold;
        QD CrQd = new QD(CenterX, CenterXLo, CenterX2, CenterX3);
        QD CiQd = new QD(CenterY, CenterYLo, CenterY2, CenterY3);
        double Cr = useExtendedRef ? (double)CrQd : CenterX;
        double Ci = useExtendedRef ? (double)CiQd : CenterY;
        var refZr = new double[maxIt + 1];
        var refZi = new double[maxIt + 1];
        // DD-precision low limbs of the reference orbit. Populated in the
        // QD branch from the next limb of the QuadDouble iterate; in the
        // double-only branch we leave them zero (Lo == 0 means a DD with
        // the Hi as its only significant bits — correct semantics).
        var refZrLo = new double[maxIt + 1];
        var refZiLo = new double[maxIt + 1];

        // Tier 5 BLA tables. Per-iteration linear coefficients
        //   A_n = ∂p/∂z(Z_n, C)  — multiplier on δ
        //   B_n = ∂p/∂c(Z_n, C)  — multiplier on ε
        // and a validity radius |Z_n|·BlaRelative beyond which the linear
        // step is rejected and the full perturbation expansion runs. Both
        // arrays are built alongside the reference orbit so they cost one
        // extra pass over the same Z trajectory.
        double[]? blaAr = null, blaAi = null, blaBr = null, blaBi = null, blaR = null;
        const double BlaRelative = 1.0e-3;
        if (UseBla)
        {
            blaAr = new double[maxIt];
            blaAi = new double[maxIt];
            blaBr = new double[maxIt];
            blaBi = new double[maxIt];
            blaR  = new double[maxIt];
        }
        if (useExtendedRef)
        {
            // ── QD reference orbit (Big+ deep zoom) ──────────────────────────
            // Iterate the polynomial step in QuadDouble precision. The high
            // limb is downcast into refZr/refZi each step for the per-pixel
            // δ math; the next iteration uses the full QD state so round-off
            // does not accumulate at double-precision rate. Outer QD locals
            // are suffixed `_q` so the inner BLA scope can re-bind the
            // (zr, zi, Cr, Ci) names that the BLA-A and BLA-B emitted
            // bodies reference by literal name.
            QD zr_q = QD.Zero, zi_q = QD.Zero;
            int n;
            for (n = 0; n < maxIt; n++)
            {
                double zrHi = zr_q.X0, ziHi = zi_q.X0;
                double r2 = zrHi * zrHi + ziHi * ziHi;
                // Ref orbit escape → bail this whole frame to the per-pixel
                // HP-direct fallback. Returning false hands control back to
                // Calculate(), which picks DD or QD direct iteration based
                // on zoom — matching what MandelbrotCalculator does when
                // ComputePixelPT can't track a pixel.
                if (r2 >= Bailout2) return false;
                refZr[n] = zrHi;
                refZi[n] = ziHi;
                refZrLo[n] = zr_q.X1;
                refZiLo[n] = zi_q.X1;
                if (UseBla)
                {
                    // BLA coefficients evaluated at the high-limb Z. The
                    // linear δ-step uses double math; pulling lower QD limbs
                    // into it would slow it without improving the answer at
                    // the accuracy a |δ| ≪ |Z| step requires.
                    double zr = zrHi, zi = ziHi;
                    double cr = Cr, ci = Ci;
{{BLA_A_BODY}}
{{BLA_B_BODY}}
                    blaAr![n] = Ar_new; blaAi![n] = Ai_new;
                    blaBr![n] = Br_new; blaBi![n] = Bi_new;
                    blaR![n]  = BlaRelative * Math.Sqrt(r2);
                }
                {
{{QD_Z_BODY}}
                    zr_q = zr_q_new; zi_q = zi_q_new;
                }
            }
            refZr[maxIt] = zr_q.X0; refZi[maxIt] = zi_q.X0;
            refZrLo[maxIt] = zr_q.X1; refZiLo[maxIt] = zi_q.X1;
        }
        else
        {
            double zr = 0.0, zi = 0.0;
            int n;
            for (n = 0; n < maxIt; n++)
            {
                double r2 = zr * zr + zi * zi;
                if (r2 >= Bailout2) return false;
                refZr[n] = zr;
                refZi[n] = zi;
                if (UseBla)
                {
                    double cr = Cr, ci = Ci;
{{BLA_A_BODY}}
{{BLA_B_BODY}}
                    blaAr![n] = Ar_new; blaAi![n] = Ai_new;
                    blaBr![n] = Br_new; blaBi![n] = Bi_new;
                    blaR![n]  = BlaRelative * Math.Sqrt(r2);
                }
                // Reuse the scalar z-update body (no derivative needed for ref orbit).
                {
                    double cr = Cr, ci = Ci;
                    double dr = 0.0, di = 0.0;          // unused; kept so SCALAR_Z_BODY parses
{{SCALAR_Z_BODY}}
                    zr = zr_new; zi = zi_new;
                }
            }
            refZr[maxIt] = zr; refZi[maxIt] = zi;
        }

        // Label reflects the perturbation tier actually chosen. Set AFTER
        // the ref orbit succeeds so a failure can't lie to the status bar.
        // QD-PT = QD reference orbit + double δ (per-pixel HP-direct on
        // glitch). PT = plain-double everything.
        LastPrecisionLabel = useExtendedRef ? "QD-PT" : "PT";

        bool useBlaLocal = UseBla;
        Parallel.For(0, Height, new ParallelOptions { CancellationToken = ct }, y =>
        {
            if (ct.IsCancellationRequested) return;
            // ε is the per-pixel offset from the view centre. Compute it
            // directly as (pixelIdx − halfDim) × scale. Earlier revisions
            // went through cx = CenterX + offset → ε = cx − Cr, which loses
            // precision at deep zoom: CenterX is ~O(1) and the offset is
            // ~1e-13 at zoom 1e13, so adding the two truncates the offset
            // to a handful of bits before the subtraction recovers it.
            // The reference orbit is already iterated relative to the view
            // centre, so ε never needs to round-trip through cx.
            double ei = (y - Height * 0.5) * scale;
            int rowBase = y * Width;
            for (int x = 0; x < Width; x++)
            {
                double er = (x - Width * 0.5) * scale;
                int finalIt = maxIt;
                double finalZr = 0.0, finalZi = 0.0;

                // dz/dc derivative carries the per-pixel signal at deep
                // zoom — its magnitude grows exponentially with iteration,
                // so even when the smooth-count fractional part collapses
                // to a single float-precision value across an iteration
                // band, the distance estimate (and the surface normals
                // derived from z·conj(dz/dc)) still vary smoothly across
                // pixels. Tracked in plain double; the value can reach
                // ~10^300 before overflow, well past what we need.
                double drv = 0.0, div = 0.0;
                double finalDrv = 0.0, finalDiv = 0.0;

                double dr = 0.0, di = 0.0;     // δ
                {
                    bool glitched = false;
                    int it = 0;
                    for (; it < maxIt; it++)
                    {
                        double Zr = refZr[it], Zi = refZi[it];
                        double zr = Zr + dr, zi = Zi + di;
                        // Glitch: δ absorbed by Z. Pixel falls to per-pixel
                        // DD-direct after the loop.
                        if (zr == Zr && zi == Zi && (dr != 0.0 || di != 0.0))
                        {
                            glitched = true;
                            break;
                        }
                        double r2 = zr * zr + zi * zi;
                        if (r2 >= Bailout2)
                        {
                            finalIt = it; finalZr = zr; finalZi = zi;
                            finalDrv = drv; finalDiv = div;
                            goto done;
                        }
                        {
{{PERTURB_DERIV_BODY}}
                            drv = drv_new; div = div_new;
                        }
                        if (useBlaLocal)
                        {
                            // BLA: try linear step. Valid when |δ| stays well
                            // below BlaRelative · |Z_n|. Otherwise fall through
                            // to the full perturbation step.
                            double dMag2 = dr * dr + di * di;
                            double rn = blaR![it];
                            if (dMag2 < rn * rn)
                            {
                                double Ar = blaAr![it], Ai = blaAi![it];
                                double Br = blaBr![it], Bi = blaBi![it];
                                double drBla = Ar * dr - Ai * di + Br * er - Bi * ei;
                                double diBla = Ar * di + Ai * dr + Br * ei + Bi * er;
                                dr = drBla; di = diBla;
                                continue;
                            }
                        }
{{PERTURB_DELTA_BODY}}
                        dr = dr_new; di = di_new;
                    }
                    if (glitched)
                    {
                        // Per-pixel HP-direct fallback. QD past the QD
                        // threshold; DD below. Cheap because glitches are
                        // rare in typical deep-zoom regions.
                        if (Zoom >= QdDirectZoomThreshold)
                        {
                            QD cxq = QD.FromCenterOffset(
                                new QD(CenterX, CenterXLo, CenterX2, CenterX3),
                                x - Width * 0.5, scale);
                            QD cyq = QD.FromCenterOffset(
                                new QD(CenterY, CenterYLo, CenterY2, CenterY3),
                                y - Height * 0.5, scale);
                            ColorBuffer[rowBase + x] = ComputePixelQdDirect(cxq, cyq, maxIt);
                        }
                        else
                        {
                            DD cxd = DD.FromCenterOffset(
                                new DD(CenterX, CenterXLo), x - Width * 0.5, scale);
                            DD cyd = DD.FromCenterOffset(
                                new DD(CenterY, CenterYLo), y - Height * 0.5, scale);
                            ColorBuffer[rowBase + x] = ComputePixelDdDirect(cxd, cyd, maxIt);
                        }
                        continue;
                    }
                    {
                        double Zr = refZr[maxIt], Zi = refZi[maxIt];
                        finalZr = Zr + dr; finalZi = Zi + di;
                        finalDrv = drv; finalDiv = div;
                    }
                    done:
                    ColorBuffer[rowBase + x] = ColorFor(finalIt, finalZr, finalZi, finalDrv, finalDiv, maxIt);
                }
            }
        });
        return true;
    }

    // ── HP-direct per-pixel fallback ─────────────────────────────────────────
    //
    // Iterates z = p(z, c) per pixel directly in DoubleDouble (~31 digits)
    // or QuadDouble (~62 digits) precision. Used when the perturbation
    // reference orbit escapes — perturbation needs a non-escaping centre,
    // so when the user zooms into a region where every reasonable centre
    // escapes, the only correct option is to drop perturbation and pay the
    // full HP per-pixel cost (matches MandelbrotCalculator's behaviour).
    //
    // Quad-double engages above QdDirectZoomThreshold (default 1e25). The
    // derivative dz/dc is tracked in plain double — its magnitude can
    // reach ~10^300 before overflow, while only direction matters for the
    // normal / distance estimate the colour map consumes.

    // Per-pixel DD direct iteration. Returns the colour for one pixel
    // whose `c` value is given as a DD. Also called from the perturbation
    // path's glitch branch — one slow pixel is much cheaper than one
    // wrong pixel, and the glitch population is typically a few percent.
    private uint ComputePixelDdDirect(DD cr_dd, DD ci_dd, int maxIt)
    {
        DD zr_dd = DD.Zero, zi_dd = DD.Zero;
        double drv = 0.0, div = 0.0;
        double finalZr = 0.0, finalZi = 0.0;
        int it = 0;
        for (; it < maxIt; it++)
        {
            double zrHi = zr_dd.Hi, ziHi = zi_dd.Hi;
            if (zrHi * zrHi + ziHi * ziHi >= Bailout2)
            {
                finalZr = zrHi; finalZi = ziHi;
                break;
            }
            {
                double zr = zrHi, zi = ziHi;
                double Cr = 0.0, Ci = 0.0;
                double cr = Cr, ci = Ci;
{{PERTURB_DERIV_BODY}}
                drv = drv_new; div = div_new;
            }
{{DD_DIRECT_BODY}}
            zr_dd = zr_dd_new; zi_dd = zi_dd_new;
        }
        return ColorFor(it, finalZr, finalZi, drv, div, maxIt);
    }

    // Per-pixel QD direct iteration — engaged above QdDirectZoomThreshold.
    private uint ComputePixelQdDirect(QD cr_q, QD ci_q, int maxIt)
    {
        QD zr_q = QD.Zero, zi_q = QD.Zero;
        double drv = 0.0, div = 0.0;
        double finalZr = 0.0, finalZi = 0.0;
        int it = 0;
        for (; it < maxIt; it++)
        {
            double zrHi = zr_q.X0, ziHi = zi_q.X0;
            if (zrHi * zrHi + ziHi * ziHi >= Bailout2)
            {
                finalZr = zrHi; finalZi = ziHi;
                break;
            }
            {
                double zr = zrHi, zi = ziHi;
                double Cr = 0.0, Ci = 0.0;
                double cr = Cr, ci = Ci;
{{PERTURB_DERIV_BODY}}
                drv = drv_new; div = div_new;
            }
{{QD_DIRECT_BODY}}
            zr_q = zr_q_new; zi_q = zi_q_new;
        }
        return ColorFor(it, finalZr, finalZi, drv, div, maxIt);
    }

    private void TryRenderHpDirect(double scale, CancellationToken ct)
    {
        bool useQd = Zoom >= QdDirectZoomThreshold;
        LastPrecisionLabel = useQd ? "QD-HP" : "DD-HP";
        int maxIt = MaxIterations;
        double halfW = Width * 0.5;
        double halfH = Height * 0.5;
        QD centerXQd = new QD(CenterX, CenterXLo, CenterX2, CenterX3);
        QD centerYQd = new QD(CenterY, CenterYLo, CenterY2, CenterY3);
        DD centerXDd = new DD(CenterX, CenterXLo);
        DD centerYDd = new DD(CenterY, CenterYLo);

        Parallel.For(0, Height, new ParallelOptions { CancellationToken = ct }, y =>
        {
            if (ct.IsCancellationRequested) return;
            int rowBase = y * Width;
            double dy = y - halfH;

            if (useQd)
            {
                QD ci_q = QD.FromCenterOffset(centerYQd, dy, scale);
                for (int x = 0; x < Width; x++)
                {
                    QD cr_q = QD.FromCenterOffset(centerXQd, x - halfW, scale);
                    ColorBuffer[rowBase + x] = ComputePixelQdDirect(cr_q, ci_q, maxIt);
                }
            }
            else
            {
                DD ci_dd = DD.FromCenterOffset(centerYDd, dy, scale);
                for (int x = 0; x < Width; x++)
                {
                    DD cr_dd = DD.FromCenterOffset(centerXDd, x - halfW, scale);
                    ColorBuffer[rowBase + x] = ComputePixelDdDirect(cr_dd, ci_dd, maxIt);
                }
            }
        });
    }

    // ── Colour mapping ──────────────────────────────────────────────────────
    //
    // Uses the nine-parameter IColorMap.Map overload so themes get smooth
    // count, distance estimate, normal direction, final z, and final dz/dc.
    // Themes that ignore these inherit the default 3-arg fallback via the
    // interface's default implementations.

    private uint ColorFor(int it, double zr, double zi, double dr, double di, int maxIt)
    {
        if (it >= maxIt) return ColorMap.InSetColor;

        double zMag2 = zr * zr + zi * zi;
        double zMag  = Math.Sqrt(zMag2);
        double dMag2 = dr * dr + di * di;
        double dMag  = Math.Sqrt(dMag2);

        // Smooth iteration count: standard log-log normalisation.
        float smooth = (float)(it + 1.0
            - Math.Log2(Math.Max(1e-10, Math.Log2(Math.Max(zMag, 1.0 + 1e-10)))));

        // Surface normal (Inigo Quilez): u + v·i  ∝  z · conj(dz/dc)
        //   u = zr·dr + zi·di
        //   v = zi·dr − zr·di
        double u = zr * dr + zi * di;
        double v = zi * dr - zr * di;
        double m = Math.Sqrt(u * u + v * v);
        float nx = 0f, ny = 0f;
        if (m > 1e-30) { nx = (float)(u / m); ny = (float)(v / m); }

        // Exterior distance estimate (Milnor / Hubbard):
        //   d ≈ 0.5 · |z| · log|z| / |dz/dc|
        // Returned in complex-plane units; themes scale by _lastPixelScale.
        float distance = 0f;
        if (dMag > 1e-30 && zMag > 1.0)
            distance = (float)(0.5 * zMag * Math.Log(zMag) / dMag);

        return (uint)ColorMap.Map(
            smooth, distance, maxIt, nx, ny,
            (float)zr, (float)zi, (float)dr, (float)di);
    }
}
