// {{CLASS_NAME}}SelfTest.cs — GENERATED by CalculatorGen --selftest
//
// Validates that the AVX2 path matches the scalar reference path of
// {{CLASS_NAME}} on a fixed sample grid. Compares per-pixel iteration
// counts; FMA rounding lets the two paths differ by at most 1 iteration
// at boundary pixels (a single ULP shift in the bailout-radius test),
// so the tolerance is `maxAbsDiff ≤ 1`.
//
// Also smoke-tests the ILGPU GPU path: builds the same sample grid as
// a full Calculate() call with UseGpu = true, reads the resulting colour
// buffer, and compares the per-pixel iteration count by re-deriving it
// from the smooth count cached in the colour map's pre-pass. If the GPU
// path is unavailable (no device, ILGPU init failure) the GPU section
// is skipped and the scalar↔AVX2 result still decides PASS/FAIL.
//
// Usage
//   var ok = {{CLASS_NAME}}SelfTest.Run(out var report);
//   Console.WriteLine(report);

using System;
using System.Runtime.Intrinsics;
using System.Text;

namespace FracturingFog.Calculators.Generated;

public static class {{CLASS_NAME}}SelfTest
{
    public const int GridWidth  = 64;
    public const int GridHeight = 64;
    public const int Iterations = 256;
    public const int Tolerance  = 1;   // ≤1 iteration count drift per pixel

    public static bool Run(out string report)
    {
        var calc = new {{CLASS_NAME}}(GridWidth, GridHeight) { MaxIterations = Iterations };

        const double centerX = -0.75;
        const double centerY =  0.0;
        const double span    =  3.5;
        double scale = span / GridWidth;

        int totalPixels = 0;
        int mismatches  = 0;
        int maxAbsDiff  = 0;
        double sumAbsDiff = 0.0;

        Span<int> avxOut = stackalloc int[4];

        for (int y = 0; y < GridHeight; y++)
        {
            double cy = centerY + (y - GridHeight * 0.5) * scale;
            for (int xStart = 0; xStart + 4 <= GridWidth; xStart += 4)
            {
                double cx0 = centerX + (xStart     - GridWidth * 0.5) * scale;
                double cx1 = centerX + (xStart + 1 - GridWidth * 0.5) * scale;
                double cx2 = centerX + (xStart + 2 - GridWidth * 0.5) * scale;
                double cx3 = centerX + (xStart + 3 - GridWidth * 0.5) * scale;

                int s0 = calc.IteratePixelScalarRaw(cx0, cy, out _, out _, out _, out _);
                int s1 = calc.IteratePixelScalarRaw(cx1, cy, out _, out _, out _, out _);
                int s2 = calc.IteratePixelScalarRaw(cx2, cy, out _, out _, out _, out _);
                int s3 = calc.IteratePixelScalarRaw(cx3, cy, out _, out _, out _, out _);

                var crVec = Vector256.Create(cx0, cx1, cx2, cx3);
                var ciVec = Vector256.Create(cy);
                calc.IterateLaneAvx2Raw(crVec, ciVec, avxOut);

                int d0 = Math.Abs(s0 - avxOut[0]);
                int d1 = Math.Abs(s1 - avxOut[1]);
                int d2 = Math.Abs(s2 - avxOut[2]);
                int d3 = Math.Abs(s3 - avxOut[3]);

                foreach (int d in new[] { d0, d1, d2, d3 })
                {
                    totalPixels++;
                    sumAbsDiff += d;
                    if (d > 0) mismatches++;
                    if (d > maxAbsDiff) maxAbsDiff = d;
                }
            }
        }

        bool avxOk = maxAbsDiff <= Tolerance;

        // ── GPU smoke ────────────────────────────────────────────────────────
        // Best-effort. Counts the in-set pixel count from both paths and
        // compares; an exact match is expected because the GPU kernel runs
        // the same scalar body. Init failure is reported but does not fail
        // the overall self-test.
        string gpuLine;
        bool gpuOk = true;
        try
        {
            using var gpuCalc = new {{CLASS_NAME}}(GridWidth, GridHeight)
            {
                MaxIterations = Iterations,
                UseGpu        = true,
                CenterX       = centerX,
                CenterY       = centerY,
                Zoom          = 3.5 / span,    // matches the scalar grid spacing
            };
            gpuCalc.Calculate();
            uint inSetColor = gpuCalc.ColorMap.InSetColor;
            int gpuInSet = 0;
            foreach (uint px in gpuCalc.ColorBuffer) if (px == inSetColor) gpuInSet++;

            int cpuInSet = 0;
            for (int yy = 0; yy < GridHeight; yy++)
            {
                double cy = centerY + (yy - GridHeight * 0.5) * scale;
                for (int xx = 0; xx < GridWidth; xx++)
                {
                    double cx = centerX + (xx - GridWidth * 0.5) * scale;
                    int it = calc.IteratePixelScalarRaw(cx, cy, out _, out _, out _, out _);
                    if (it >= Iterations) cpuInSet++;
                }
            }

            int gpuDiff = Math.Abs(gpuInSet - cpuInSet);
            gpuOk = gpuDiff <= 4;   // tolerance: ≤4 boundary pixels
            gpuLine = $"  gpu in-set:     cpu={cpuInSet}  gpu={gpuInSet}  diff={gpuDiff}  → {(gpuOk ? "PASS" : "FAIL")}";
        }
        catch (Exception ex)
        {
            gpuLine = $"  gpu in-set:     SKIP ({ex.GetType().Name}: {ex.Message})";
            gpuOk = true;   // unavailable, not a hard failure
        }

        // ── Perturbation smoke (Tier 4) ──────────────────────────────────────
        // Same in-set comparison style as the GPU smoke. Force the threshold
        // to 0 so the perturbation path runs even at the default Zoom.
        string ptLine;
        bool ptOk = true;
        try
        {
            using var ptCalc = new {{CLASS_NAME}}(GridWidth, GridHeight)
            {
                MaxIterations        = Iterations,
                UsePerturbation      = true,
                PerturbZoomThreshold = 0.0,
                CenterX              = centerX,
                CenterY              = centerY,
                Zoom                 = 3.5 / span,
            };
            ptCalc.Calculate();
            uint inSetColor = ptCalc.ColorMap.InSetColor;
            int ptInSet = 0;
            foreach (uint px in ptCalc.ColorBuffer) if (px == inSetColor) ptInSet++;

            int cpuInSet = 0;
            for (int yy = 0; yy < GridHeight; yy++)
            {
                double cy = centerY + (yy - GridHeight * 0.5) * scale;
                for (int xx = 0; xx < GridWidth; xx++)
                {
                    double cx = centerX + (xx - GridWidth * 0.5) * scale;
                    int it = calc.IteratePixelScalarRaw(cx, cy, out _, out _, out _, out _);
                    if (it >= Iterations) cpuInSet++;
                }
            }

            int ptDiff = Math.Abs(ptInSet - cpuInSet);
            ptOk = ptDiff <= 4;
            ptLine = $"  perturbation:   cpu={cpuInSet}  pt={ptInSet}  diff={ptDiff}  → {(ptOk ? "PASS" : "FAIL")}";
        }
        catch (Exception ex)
        {
            ptLine = $"  perturbation:   FAIL ({ex.GetType().Name}: {ex.Message})";
            ptOk = false;
        }

        // ── BLA smoke (Tier 5) ───────────────────────────────────────────────
        // Linear-step path enabled. Same in-set comparison as the others.
        // BLA accepts up to ~4 pixel drift at boundaries because the linear
        // step truncates the δ² contribution where validity holds.
        string blaLine;
        bool blaOk = true;
        try
        {
            using var blaCalc = new {{CLASS_NAME}}(GridWidth, GridHeight)
            {
                MaxIterations        = Iterations,
                UsePerturbation      = true,
                UseBla               = true,
                PerturbZoomThreshold = 0.0,
                CenterX              = centerX,
                CenterY              = centerY,
                Zoom                 = 3.5 / span,
            };
            blaCalc.Calculate();
            uint inSetColor = blaCalc.ColorMap.InSetColor;
            int blaInSet = 0;
            foreach (uint px in blaCalc.ColorBuffer) if (px == inSetColor) blaInSet++;

            int cpuInSet = 0;
            for (int yy = 0; yy < GridHeight; yy++)
            {
                double cy = centerY + (yy - GridHeight * 0.5) * scale;
                for (int xx = 0; xx < GridWidth; xx++)
                {
                    double cx = centerX + (xx - GridWidth * 0.5) * scale;
                    int it = calc.IteratePixelScalarRaw(cx, cy, out _, out _, out _, out _);
                    if (it >= Iterations) cpuInSet++;
                }
            }

            int blaDiff = Math.Abs(blaInSet - cpuInSet);
            blaOk = blaDiff <= 8;   // BLA tolerates a few extra boundary pixels
            blaLine = $"  bla:            cpu={cpuInSet}  bla={blaInSet}  diff={blaDiff}  → {(blaOk ? "PASS" : "FAIL")}";
        }
        catch (Exception ex)
        {
            blaLine = $"  bla:            FAIL ({ex.GetType().Name}: {ex.Message})";
            blaOk = false;
        }

        // ── Extended-ref QD smoke (Big+) ─────────────────────────────────────
        // Force the QD reference orbit by raising Zoom past
        // ExtendedRefZoomThreshold and supplying a non-zero CenterXLo (zero
        // value is fine; the path only checks for any non-zero limb to
        // detect "caller plumbed extended precision"). Verifies the QD
        // branch executes end-to-end without exceptions and produces a
        // mix of in-set / out-of-set pixels (i.e. didn't return false →
        // CPU fallback).
        string qdLine;
        bool qdOk = true;
        try
        {
            using var qdCalc = new {{CLASS_NAME}}(GridWidth, GridHeight)
            {
                MaxIterations            = Iterations,
                UsePerturbation          = true,
                PerturbZoomThreshold     = 0.0,
                ExtendedRefZoomThreshold = 0.0,
                CenterX                  = centerX,
                CenterY                  = centerY,
                CenterXLo                = 1.0e-30,    // forces useExtendedRef = true
                Zoom                     = 3.5 / span,
            };
            qdCalc.Calculate();
            uint inSetColor = qdCalc.ColorMap.InSetColor;
            int qdInSet = 0, qdOutSet = 0;
            foreach (uint px in qdCalc.ColorBuffer)
            {
                if (px == inSetColor) qdInSet++; else qdOutSet++;
            }
            // Sanity: full grid must have both in-set and out-of-set pixels.
            qdOk = qdInSet > 0 && qdOutSet > 0;
            qdLine = $"  qd ref orbit:   in-set={qdInSet}  out={qdOutSet}  → {(qdOk ? "PASS" : "FAIL")}";
        }
        catch (Exception ex)
        {
            qdLine = $"  qd ref orbit:   FAIL ({ex.GetType().Name}: {ex.Message})";
            qdOk = false;
        }

        bool ok = avxOk && gpuOk && ptOk && blaOk && qdOk;

        var sb = new StringBuilder();
        sb.AppendLine($"{nameof({{CLASS_NAME}}SelfTest)} — scalar ↔ AVX2 ↔ GPU agreement");
        sb.AppendLine($"  grid:           {GridWidth}×{GridHeight} = {totalPixels} pixels");
        sb.AppendLine($"  max iterations: {Iterations}");
        sb.AppendLine($"  mismatches:     {mismatches} ({(totalPixels == 0 ? 0.0 : 100.0 * mismatches / totalPixels):F2}%)");
        sb.AppendLine($"  mean |Δit|:     {(totalPixels == 0 ? 0.0 : sumAbsDiff / totalPixels):F4}");
        sb.AppendLine($"  max  |Δit|:     {maxAbsDiff}  (tolerance: {Tolerance})");
        sb.AppendLine(gpuLine);
        sb.AppendLine(ptLine);
        sb.AppendLine(blaLine);
        sb.AppendLine(qdLine);
        sb.AppendLine($"  result:         {(ok ? "PASS" : "FAIL")}");
        report = sb.ToString();
        return ok;
    }
}
