// TwoToneMoonTheme.cs — GENERATED by ColorGen
//
// Source DSL:
// //   let lit = nx*0.5 + ny*0.5 + 0.5;
//       return lit > 0.6 ? rgb(1, 1, 1) : rgb(0.05, 0.05, 0.20);
//
// Generator: ColorGen v0.1 (algorithmic colour theme)
// Generated: 2026-06-02 20:30:06 UTC
//
// DO NOT HAND-EDIT. Re-run ColorGen with the same --name flag to regenerate.

using System;
using System.Runtime.CompilerServices;

using FracturingFog.Interefaces;
using FracturingFog.Models;

namespace FracturingFog.Models.Generated;

public sealed class TwoToneMoonTheme : IColorMap, INamedColorMap
{
    public static string Name => "Two Tone Moon";
    public static string Category => "User";
    public static string Description => "";

    public string DisplayName        => Name;
    public string DisplayCategory    => Category;
    public string DisplayDescription => Description;

    public ColorPaletteType Type => ColorPaletteType.Algorithmic;

    public int MaxIterations { get; set; } = 512;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public int Map(float smooth, float distance, int iterations)
        => Map(smooth, distance, iterations, 0f, 0f, 0f, 0f, 0f, 0f);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public int Map(float smooth, float distance, int iterations, float nx, float ny)
        => Map(smooth, distance, iterations, nx, ny, 0f, 0f, 0f, 0f);

    public int Map(float smooth, float distance, int iterations,
                   float nx, float ny,
                   float finalZr, float finalZi, float dzdcR, float dzdcI)
    {
        // ── Input adapter: surface every DSL input as an in_* local. ──────
        double in_smooth  = smooth;
        double in_dist    = distance;
        double in_iter    = (double)iterations;
        double in_maxIter = (double)MaxIterations;
        double in_t       = MaxIterations > 0 ? smooth / (double)MaxIterations : 0.0;
        double in_nx      = nx;
        double in_ny      = ny;
        double in_zr      = finalZr;
        double in_zi      = finalZi;
        double in_dzr     = dzdcR;
        double in_dzi     = dzdcI;
        double in_arg     = System.Math.Atan2((double)finalZi, (double)finalZr);
        double in_mag     = System.Math.Sqrt((double)finalZr * finalZr + (double)finalZi * finalZi);
        double in_isInSet = iterations >= MaxIterations ? 1.0 : 0.0;

        double v_lit = (((in_nx * 0.5D) + (in_ny * 0.5D)) + 0.5D);
        return PackArgb((((v_lit >  0.6D ? 1.0 : 0.0)) != 0.0 ? new Cg3(1D, 1D, 1D) : new Cg3(0.05D, 0.05D, 0.2D)));

    }

    // ── Runtime helpers (Cg3 + scalar utilities + ARGB packer) ───────────

    private static int PackArgb(Cg3 c)
    {
        int r = (int)(System.Math.Clamp(c.R, 0.0, 1.0) * 255.0 + 0.5);
        int g = (int)(System.Math.Clamp(c.G, 0.0, 1.0) * 255.0 + 0.5);
        int b = (int)(System.Math.Clamp(c.B, 0.0, 1.0) * 255.0 + 0.5);
        return unchecked((int)0xFF000000) | (r << 16) | (g << 8) | b;
    }

    internal readonly record struct Cg3(double R, double G, double B)
    {
        // ── Elementwise + - * / on Cg3↔Cg3 (Cg3↔Scalar variants follow). ──
        public static Cg3 Add(Cg3 a, Cg3 b) => new(a.R + b.R, a.G + b.G, a.B + b.B);
        public static Cg3 AddVS(Cg3 a, double s) => new(a.R + s, a.G + s, a.B + s);
        public static Cg3 AddSV(double s, Cg3 a) => new(s + a.R, s + a.G, s + a.B);
        public static Cg3 Sub(Cg3 a, Cg3 b) => new(a.R - b.R, a.G - b.G, a.B - b.B);
        public static Cg3 SubVS(Cg3 a, double s) => new(a.R - s, a.G - s, a.B - s);
        public static Cg3 SubSV(double s, Cg3 a) => new(s - a.R, s - a.G, s - a.B);
        public static Cg3 Mul(Cg3 a, Cg3 b) => new(a.R * b.R, a.G * b.G, a.B * b.B);
        public static Cg3 MulVS(Cg3 a, double s) => new(a.R * s, a.G * s, a.B * s);
        public static Cg3 MulSV(double s, Cg3 a) => new(s * a.R, s * a.G, s * a.B);
        public static Cg3 Div(Cg3 a, Cg3 b) => new(a.R / b.R, a.G / b.G, a.B / b.B);
        public static Cg3 DivVS(Cg3 a, double s) => new(a.R / s, a.G / s, a.B / s);
        public static Cg3 DivSV(double s, Cg3 a) => new(s / a.R, s / a.G, s / a.B);
        public static Cg3 Neg(Cg3 a) => new(-a.R, -a.G, -a.B);

        public static Cg3 Mod(Cg3 a, Cg3 b)
            => new(CgScalar.Mod(a.R, b.R), CgScalar.Mod(a.G, b.G), CgScalar.Mod(a.B, b.B));
        public static Cg3 ModVS(Cg3 a, double s)
            => new(CgScalar.Mod(a.R, s), CgScalar.Mod(a.G, s), CgScalar.Mod(a.B, s));
        public static Cg3 ModSV(double s, Cg3 a)
            => new(CgScalar.Mod(s, a.R), CgScalar.Mod(s, a.G), CgScalar.Mod(s, a.B));

        public static Cg3 Pow(Cg3 a, Cg3 b)
            => new(System.Math.Pow(a.R, b.R), System.Math.Pow(a.G, b.G), System.Math.Pow(a.B, b.B));
        public static Cg3 PowVS(Cg3 a, double s)
            => new(System.Math.Pow(a.R, s), System.Math.Pow(a.G, s), System.Math.Pow(a.B, s));
        public static Cg3 PowSV(double s, Cg3 a)
            => new(System.Math.Pow(s, a.R), System.Math.Pow(s, a.G), System.Math.Pow(s, a.B));

        public static Cg3 Mix(Cg3 a, Cg3 b, double t)
            => new(a.R + (b.R - a.R) * t,
                   a.G + (b.G - a.G) * t,
                   a.B + (b.B - a.B) * t);

        public static Cg3 FromHsv(double h, double s, double v)
        {
            // Cyclic hue in [0,1). HSV→RGB with the standard 6-segment lookup.
            h = h - System.Math.Floor(h);
            s = System.Math.Clamp(s, 0.0, 1.0);
            v = System.Math.Clamp(v, 0.0, 1.0);
            double hh = h * 6.0;
            int i = (int)System.Math.Floor(hh);
            double f = hh - i;
            double p = v * (1.0 - s);
            double q = v * (1.0 - f * s);
            double tt = v * (1.0 - (1.0 - f) * s);
            return (i % 6) switch
            {
                0 => new Cg3(v, tt, p),
                1 => new Cg3(q, v, p),
                2 => new Cg3(p, v, tt),
                3 => new Cg3(p, q, v),
                4 => new Cg3(tt, p, v),
                _ => new Cg3(v, p, q),
            };
        }

        public static Cg3 FromHsl(double h, double s, double l)
        {
            h = h - System.Math.Floor(h);
            s = System.Math.Clamp(s, 0.0, 1.0);
            l = System.Math.Clamp(l, 0.0, 1.0);
            double c = (1.0 - System.Math.Abs(2.0 * l - 1.0)) * s;
            double hh = h * 6.0;
            double x = c * (1.0 - System.Math.Abs((hh % 2.0) - 1.0));
            double m = l - c * 0.5;
            double r1, g1, b1;
            int seg = (int)System.Math.Floor(hh);
            switch (seg % 6)
            {
                case 0: r1 = c; g1 = x; b1 = 0; break;
                case 1: r1 = x; g1 = c; b1 = 0; break;
                case 2: r1 = 0; g1 = c; b1 = x; break;
                case 3: r1 = 0; g1 = x; b1 = c; break;
                case 4: r1 = x; g1 = 0; b1 = c; break;
                default:r1 = c; g1 = 0; b1 = x; break;
            }
            return new Cg3(r1 + m, g1 + m, b1 + m);
        }

        /// <summary>Cyclic linear palette: stops are evenly spaced on [0,1)
        /// with t wrapping (fract). With N stops the segment for t lands in
        /// [k/N, (k+1)/N) and lerps between stops[k] and stops[(k+1)%N].</summary>
        public static Cg3 Palette(double t, params Cg3[] stops)
        {
            int n = stops.Length;
            if (n == 0) return new Cg3(0, 0, 0);
            if (n == 1) return stops[0];
            double frac = t - System.Math.Floor(t);
            double pos = frac * n;
            int k = (int)System.Math.Floor(pos) % n;
            int k2 = (k + 1) % n;
            double f = pos - System.Math.Floor(pos);
            return Mix(stops[k], stops[k2], f);
        }

        public static Cg3 Brightness(Cg3 a, double s) => new(a.R + s, a.G + s, a.B + s);

        public static Cg3 Contrast(Cg3 a, double s)
        {
            // s in [-1,1]: -1 = grey, 0 = identity, 1 = double contrast.
            double f = 1.0 + s;
            return new(0.5 + (a.R - 0.5) * f,
                       0.5 + (a.G - 0.5) * f,
                       0.5 + (a.B - 0.5) * f);
        }

        public static Cg3 Gamma(Cg3 a, double g)
        {
            double e = g <= 0.0 ? 1.0 : 1.0 / g;
            return new(System.Math.Pow(System.Math.Max(0, a.R), e),
                       System.Math.Pow(System.Math.Max(0, a.G), e),
                       System.Math.Pow(System.Math.Max(0, a.B), e));
        }
    }

    internal static class CgScalar
    {
        public static double Fract(double x) => x - System.Math.Floor(x);

        public static double Hypot(double x, double y) => System.Math.Sqrt(x * x + y * y);

        public static double Mod(double x, double y)
        {
            // GLSL-style mod: x - y * floor(x/y). Differs from C# % on negatives.
            if (y == 0.0) return 0.0;
            return x - y * System.Math.Floor(x / y);
        }

        public static double Smoothstep(double edge0, double edge1, double x)
        {
            double t = (x - edge0) / (edge1 - edge0);
            if (t < 0.0) t = 0.0; else if (t > 1.0) t = 1.0;
            return t * t * (3.0 - 2.0 * t);
        }

        public static double Hash(double x)
        {
            // Cheap deterministic noise: fract(sin(x * 12.9898) * 43758.5453).
            return Fract(System.Math.Sin(x * 12.9898) * 43758.5453);
        }

        public static double Hash2(double x, double y)
        {
            return Fract(System.Math.Sin(x * 12.9898 + y * 78.233) * 43758.5453);
        }
    }
}
