// Auto-generated by Color Theme Editor.
// Drop into Models/ColorSchemes (or any sub-folder of FracturingFog.Models).
// Register by adding `new AlienBandedTheme()` to ColorPalette.BuiltIns.

using System.Drawing;
using FracturingFog.Interefaces;

namespace FracturingFog.Models
{
    public sealed class AlienBandedTheme : GradientPhong3DBase, IThemePostFx
    {
        public static string Name => "Alien Banded";
        public static string Category => "3D Relief";
        public static string Description => "Alien Red Banded Apadptive";

        protected override float CycleSpeed => 0.03F;
        protected override float Steepness => 2.4F;
        protected override float Ambient => 0.38F;
        protected override float KeySpecScale => 0.72F;
        protected override float FillSpecScale => 0.26F;
        protected override float FillDiffScale => 0.74F;

        public AlienBandedTheme()
        {
            Stops.Add(new ColorStop(0F, Color.FromArgb(0, 0, 0)));
            Stops.Add(new ColorStop(0.2F, Color.FromArgb(0, 32, 61)));
            Stops.Add(new ColorStop(0.4F, Color.FromArgb(0, 55, 128)));
            Stops.Add(new ColorStop(0.6F, Color.FromArgb(0, 255, 128)));
            Stops.Add(new ColorStop(0.8F, Color.FromArgb(145, 255, 128)));
            Stops.Add(new ColorStop(1F, Color.FromArgb(255, 255, 255)));
            KeyLight = new LightSource(
                lx: 0.761F, ly: 0.419F, lz: 0.495F,
                diffR: 0F, diffG: 0F, diffB: 0.8627451F,
                specR: 1F, specG: 0F, specB: 0F,
                shininess: 15F);
            FillLight = new LightSource(
                lx: -0.6F, ly: -0.154F, lz: 0.785F,
                diffR: 0.5647059F, diffG: 0F, diffB: 0F,
                specR: 1F, specG: 1F, specB: 0F,
                shininess: 92F);
        }

        int? IThemePostFx.ThemeBrightness => null;
        int? IThemePostFx.ThemeContrast => null;
        int? IThemePostFx.ThemeAdaptive => 17;
    }
}
