// Models/ColorThemeCsExporter.cs
//
// Shared "ColorThemeData -> compilable C# source" emitter. Lifted out of
// Views/ColorThemeEditor.cs so the legacy WinForms editor and the new
// Avalonia HostColorThemeService can both reuse the exact same output.
//
// Pure function: no Forms / Avalonia / IO dependencies. Callers handle the
// file dialog + File.WriteAllText themselves.

using System.Collections.Generic;
using System.Globalization;
using System.Text;

namespace FracturingFog.Models
{
    /// <summary>
    /// Emits a self-contained, drop-in C# class derived from
    /// <see cref="ColorThemeData"/>. The generated file targets
    /// <c>FracturingFog.Models</c> and inherits from the appropriate base
    /// (GradientColorMap / CyclingGradientColorMap / GradientPhong3DBase /
    /// PbrGradient3DBase) for the theme's <see cref="ColorThemeKind"/>.
    /// </summary>
    public static class ColorThemeCsExporter
    {
        /// <summary>
        /// Turns a theme display-name into a valid C# identifier suffixed
        /// with "Theme". Strips non-alphanumerics, upper-cases the first
        /// character after each separator, prefixes an underscore if the
        /// first remaining character is a digit. Falls back to "MyTheme"
        /// when the input is empty after stripping.
        /// </summary>
        public static string MakeClassName(string? themeName)
        {
            var sb = new StringBuilder();
            bool upper = true;
            foreach (char c in themeName ?? "")
            {
                if (char.IsLetterOrDigit(c))
                {
                    sb.Append(upper ? char.ToUpperInvariant(c) : c);
                    upper = false;
                }
                else
                {
                    upper = true;
                }
            }
            if (sb.Length == 0) sb.Append("MyTheme");
            if (char.IsDigit(sb[0])) sb.Insert(0, '_');
            sb.Append("Theme");
            return sb.ToString();
        }

        /// <summary>
        /// Generates the full C# source for a sealed class implementing
        /// <paramref name="data"/>. Output is deterministic for stable diffs.
        /// </summary>
        public static string BuildCSharpSource(ColorThemeData data, string className)
        {
            bool is3D = data.Kind == ColorThemeKind.Phong3D || data.Kind == ColorThemeKind.Pbr3D;
            bool isPbr = data.Kind == ColorThemeKind.Pbr3D;
            bool isPhong = data.Kind == ColorThemeKind.Phong3D;
            bool isCycling = data.Kind == ColorThemeKind.Cycling;
            bool hasPostFx = data.Brightness.HasValue || data.Contrast.HasValue || data.Adaptive.HasValue;
            bool hasInSet = data.InSetColor != null;
            bool emitBands = isPbr && data.MaterialBands != null && data.MaterialBands.Count > 0;
            bool emitGlow = isPbr && data.GlowBoostScale != 0f;

            string baseClass = data.Kind switch
            {
                ColorThemeKind.Gradient => "GradientColorMap",
                ColorThemeKind.Cycling => "CyclingGradientColorMap",
                ColorThemeKind.Phong3D => "GradientPhong3DBase",
                ColorThemeKind.Pbr3D => "PbrGradient3DBase",
                _ => "GradientColorMap",
            };

            var bases = new List<string> { baseClass };
            if (hasPostFx) bases.Add("IThemePostFx");

            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by Color Theme Editor.");
            sb.AppendLine("// Drop into Models/ColorSchemes (or any sub-folder of FracturingFog.Models).");
            sb.AppendLine("// Register by adding `new " + className + "()` to ColorPalette.BuiltIns.");
            sb.AppendLine();
            if (isPbr) sb.AppendLine("using System;");
            sb.AppendLine("using System.Drawing;");
            if (hasPostFx || hasInSet) sb.AppendLine("using FracturingFog.Interefaces;");
            sb.AppendLine();
            sb.AppendLine("namespace FracturingFog.Models");
            sb.AppendLine("{");
            sb.AppendLine("    public sealed class " + className + " : " + string.Join(", ", bases));
            sb.AppendLine("    {");

            sb.AppendLine("        public static string Name => " + Quote(data.Name) + ";");
            sb.AppendLine("        public static string Category => " + Quote(data.Category ?? "User") + ";");
            sb.AppendLine("        public static string Description => " + Quote(data.Description ?? "") + ";");
            if (data.MaxRecommendedZoom.HasValue && !double.IsPositiveInfinity(data.MaxRecommendedZoom.Value))
                sb.AppendLine("        public static double MaxRecommendedZoom => " + Dbl(data.MaxRecommendedZoom.Value) + ";");
            sb.AppendLine();

            if (isCycling || is3D)
                sb.AppendLine("        protected override float CycleSpeed => " + Flt(data.CycleSpeed) + ";");
            if (is3D)
            {
                sb.AppendLine("        protected override float Steepness => " + Flt(data.Steepness) + ";");
                sb.AppendLine("        protected override float Ambient => " + Flt(data.Ambient) + ";");
            }
            if (isPhong)
            {
                sb.AppendLine("        protected override float KeySpecScale => " + Flt(data.KeySpecScale) + ";");
                sb.AppendLine("        protected override float FillSpecScale => " + Flt(data.FillSpecScale) + ";");
                sb.AppendLine("        protected override float FillDiffScale => " + Flt(data.FillDiffScale) + ";");
            }
            if (isPbr)
            {
                sb.AppendLine("        protected override PbrLightingMode LightingMode => PbrLightingMode." + data.PbrLightingMode + ";");
            }
            if (isCycling || is3D || isPbr || isPhong) sb.AppendLine();

            if (emitBands)
            {
                sb.AppendLine("        private static readonly (float UpperT, float Metal, float Roughness)[] Bands = new[]");
                sb.AppendLine("        {");
                foreach (var b in data.MaterialBands!)
                {
                    sb.AppendLine("            (" + Flt(b.UpperT) + ", " + Flt(b.Metal) + ", " + Flt(b.Roughness) + "),");
                }
                sb.AppendLine("        };");
                sb.AppendLine();
            }

            sb.AppendLine("        public " + className + "()");
            sb.AppendLine("        {");
            if (data.Stops != null)
            {
                foreach (var s in data.Stops)
                {
                    sb.AppendLine("            Stops.Add(new ColorStop(" + Flt(s.Position)
                        + ", Color.FromArgb(" + s.R + ", " + s.G + ", " + s.B + ")));");
                }
            }
            if (is3D)
            {
                if (data.KeyLight != null) AppendLight(sb, "KeyLight", data.KeyLight);
                if (data.FillLight != null) AppendLight(sb, "FillLight", data.FillLight);
                if (data.RimLight != null)
                {
                    AppendLight(sb, "RimLight", data.RimLight);
                    sb.AppendLine("            UseRimLight = true;");
                }
            }
            sb.AppendLine("        }");

            if (emitBands)
            {
                sb.AppendLine();
                sb.AppendLine("        protected override PbrMaterial BuildMaterial(float t, float r, float g, float b)");
                sb.AppendLine("        {");
                sb.AppendLine("            for (int i = 0; i < Bands.Length - 1; i++)");
                sb.AppendLine("            {");
                sb.AppendLine("                if (t < Bands[i].UpperT)");
                sb.AppendLine("                    return new PbrMaterial(r, g, b, Bands[i].Metal, Bands[i].Roughness);");
                sb.AppendLine("            }");
                sb.AppendLine("            var last = Bands[Bands.Length - 1];");
                sb.AppendLine("            return new PbrMaterial(r, g, b, last.Metal, last.Roughness);");
                sb.AppendLine("        }");
            }

            if (emitGlow)
            {
                sb.AppendLine();
                sb.AppendLine("        protected override float GlowBoost(float t)");
                sb.AppendLine("            => " + Flt(data.GlowBoostScale) + " * MathF.Pow(t, " + Flt(data.GlowBoostExponent) + ");");
            }

            if (hasInSet)
            {
                uint argb = data.InSetColor!.ToPackedArgb();
                sb.AppendLine();
                sb.AppendLine("        uint IColorMap.InSetColor => 0x" + argb.ToString("X8", CultureInfo.InvariantCulture) + "u;");
            }

            if (hasPostFx)
            {
                sb.AppendLine();
                sb.AppendLine("        int? IThemePostFx.ThemeBrightness => " + NullableInt(data.Brightness) + ";");
                sb.AppendLine("        int? IThemePostFx.ThemeContrast => " + NullableInt(data.Contrast) + ";");
                sb.AppendLine("        int? IThemePostFx.ThemeAdaptive => " + NullableInt(data.Adaptive) + ";");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        // ── private helpers ───────────────────────────────────────────────

        private static void AppendLight(StringBuilder sb, string fieldName, LightSourceData l)
        {
            sb.AppendLine("            " + fieldName + " = new LightSource(");
            sb.AppendLine("                lx: " + Flt(l.Lx) + ", ly: " + Flt(l.Ly) + ", lz: " + Flt(l.Lz) + ",");
            sb.AppendLine("                diffR: " + Flt(l.DiffR) + ", diffG: " + Flt(l.DiffG) + ", diffB: " + Flt(l.DiffB) + ",");
            sb.AppendLine("                specR: " + Flt(l.SpecR) + ", specG: " + Flt(l.SpecG) + ", specB: " + Flt(l.SpecB) + ",");
            sb.AppendLine("                shininess: " + Flt(l.Shininess) + ");");
        }

        private static string NullableInt(int? v)
            => v.HasValue ? v.Value.ToString(CultureInfo.InvariantCulture) : "null";

        private static string Quote(string? s)
        {
            s ??= "";
            var sb = new StringBuilder("\"");
            foreach (char c in s)
            {
                switch (c)
                {
                    case '\\': sb.Append("\\\\"); break;
                    case '\"': sb.Append("\\\""); break;
                    case '\r': sb.Append("\\r"); break;
                    case '\n': sb.Append("\\n"); break;
                    case '\t': sb.Append("\\t"); break;
                    default: sb.Append(c); break;
                }
            }
            sb.Append('\"');
            return sb.ToString();
        }

        private static string Flt(float v)
        {
            if (float.IsNaN(v) || float.IsInfinity(v)) return "0F";
            return v.ToString("R", CultureInfo.InvariantCulture) + "F";
        }

        private static string Dbl(double v)
        {
            if (double.IsNaN(v) || double.IsInfinity(v)) return "0D";
            return v.ToString("R", CultureInfo.InvariantCulture) + "D";
        }
    }
}
