// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Bradley Brown

// {{CLASS_NAME}}.cs — GENERATED by ColorGen (orbit-aware)
//
// Source DSL:
// {{SOURCE_COMMENT}}
//
// Generator: ColorGen v0.1 (algorithmic colour theme — orbit accumulators)
// Generated: {{TIMESTAMP}}
//
// This theme references per-iteration orbit-accumulator inputs (trapMin /
// stripeAvg / curvature / …), so it implements IOrbitAwareColorMap: the
// calculator samples the orbit each iteration (InitOrbit + Sample) and binds
// the accumulated values at escape (MapWithOrbit). It advertises NO GPU palette
// — the escape-only HLSL path can't compute these — so it renders on the CPU.
// Only the accumulators the program actually reads are computed (const-bool
// gates; the JIT drops the unused branches).
//
// DO NOT HAND-EDIT. Re-run ColorGen with the same --name flag to regenerate.

using System;
using System.Runtime.CompilerServices;

using FracturingFog.Interefaces;
using FracturingFog.Models;

namespace FracturingFog.Models.Generated;

public sealed class {{CLASS_NAME}} : IColorMap, INamedColorMap, IColorMapWithPixelScale, IColorMapHandlesInSet, IOrbitAwareColorMap
{
    public static string Name => "{{THEME_NAME}}";
    public static string Category => "{{CATEGORY}}";
    public static string Description => "{{DESCRIPTION}}";

    public string DisplayName        => Name;
    public string DisplayCategory    => Category;
    public string DisplayDescription => Description;

    public ColorPaletteType Type => ColorPaletteType.Algorithmic;

    public int MaxIterations { get; set; } = 512;

    // Set per-frame by the calculator; default keeps stand-alone usage safe.
    private double _pixelScale = 1.0;
    public double PixelScale { set => _pixelScale = value; }

    // ── Which accumulators this program references (baked at generate time). ──
    // const so the JIT eliminates the unused Sample branches entirely.
    private const bool F_trapMin       = {{F_TRAPMIN}};
    private const bool F_trapCross     = {{F_TRAPCROSS}};
    private const bool F_trapRing      = {{F_TRAPRING}};
    private const bool F_trapHyperbola = {{F_TRAPHYPERBOLA}};
    private const bool F_trapHexagon   = {{F_TRAPHEXAGON}};
    private const bool F_stripe        = {{F_STRIPE}};
    private const bool F_tia           = {{F_TIA}};
    private const bool F_curvature     = {{F_CURVATURE}};
    private const bool F_lyapunov      = {{F_LYAPUNOV}};
    private const bool F_gaussian      = {{F_GAUSSIAN}};
    private const bool F_exp           = {{F_EXP}};

    // Orbit-trap geometry constants (match the built-in trap shapes).
    private const double StripeDensity = 7.0;
    private const double RingCx = -1.0, RingCy = 0.0, RingR = 0.3;

    // ── IOrbitAwareColorMap — per-iteration orbit sampling. ──────────────────

    public void InitOrbit(out OrbitAccumulator acc)
    {
        acc = default;
        acc.TrapMin  = float.MaxValue;   // trapMin  — origin point-trap
        acc.TrapMin2 = float.MaxValue;   // trapCross — nearest-axis trap
        acc.TrapMin3 = float.MaxValue;   // trapRing
        acc.TrapMin4 = float.MaxValue;   // trapHyperbola
        acc.TrapMin5 = float.MaxValue;   // trapHexagon
    }

    public void Sample(ref OrbitAccumulator acc, double zr, double zi, double cr, double ci, int iter)
    {
        // trapMin — min distance to the origin (point trap).
        if (F_trapMin)
        {
            double d = Math.Sqrt(zr * zr + zi * zi);
            if ((float)d < acc.TrapMin) acc.TrapMin = (float)d;
        }

        // trapCross — min distance to the nearer coordinate axis.
        if (F_trapCross)
        {
            double d = Math.Min(Math.Abs(zr), Math.Abs(zi));
            if ((float)d < acc.TrapMin2) acc.TrapMin2 = (float)d;
        }

        // trapRing — min distance to a circle of radius 0.3 centred at (-1, 0).
        if (F_trapRing)
        {
            double dx = zr - RingCx, dy = zi - RingCy;
            double d = Math.Abs(Math.Sqrt(dx * dx + dy * dy) - RingR);
            if ((float)d < acc.TrapMin3) acc.TrapMin3 = (float)d;
        }

        // trapHyperbola — min distance to the curve |zr·zi| = 1.
        if (F_trapHyperbola)
        {
            double f = Math.Abs(zr * zi) - 1.0;
            double gradMag = Math.Sqrt(zr * zr + zi * zi);
            if (gradMag < 1e-6) gradMag = 1e-6;
            double d = Math.Abs(f) / gradMag;
            if ((float)d < acc.TrapMin4) acc.TrapMin4 = (float)d;
        }

        // trapHexagon — min distance to a regular hexagon's edges (folded SDF).
        if (F_trapHexagon)
        {
            const double kx = -0.8660254037844387;   // −√3/2
            const double ky = 0.5;
            const double kz = 0.5773502691896257;    // tan(π/6)
            double px = Math.Abs(zr), py = Math.Abs(zi);
            double dot2 = 2.0 * Math.Min(kx * px + ky * py, 0.0);
            px -= dot2 * kx;
            py -= dot2 * ky;
            px -= Math.Clamp(px, -kz, kz);
            py -= 1.0;
            double d = Math.Sqrt(px * px + py * py);
            if ((float)d < acc.TrapMin5) acc.TrapMin5 = (float)d;
        }

        // stripeAvg — mean of 0.5 + 0.5·sin(density·arg(z_n)).
        if (F_stripe)
        {
            double s = 0.5 + 0.5 * Math.Sin(StripeDensity * Math.Atan2(zi, zr));
            acc.LastStripe = s;
            acc.StripeSum += s;
            acc.StripeCount++;
        }

        // tiaAvg — triangle-inequality average (needs a predecessor, iter >= 2).
        if (F_tia && iter >= 2)
        {
            double zMcR = zr - cr, zMcI = zi - ci;
            double absZprev2 = Math.Sqrt(zMcR * zMcR + zMcI * zMcI);
            double absC = Math.Sqrt(cr * cr + ci * ci);
            double absZ = Math.Sqrt(zr * zr + zi * zi);
            double m = Math.Abs(absZprev2 - absC);
            double M = absZprev2 + absC;
            if (M - m > 1e-12)
            {
                double t = (absZ - m) / (M - m);
                acc.LastTia = t;
                acc.TiaSum += t;
                acc.TiaCount++;
            }
        }

        // lyapunov — mean log|2 z_n| (local divergence rate).
        if (F_lyapunov)
        {
            double a = Math.Sqrt(zr * zr + zi * zi);
            if (a > 1e-12) { acc.LyapunovSum += Math.Log(2.0 * a); acc.LyapunovCount++; }
        }

        // gaussian — mean distance to the nearest Gaussian integer.
        if (F_gaussian)
        {
            double dr = zr - Math.Round(zr), di = zi - Math.Round(zi);
            acc.GaussianSum += Math.Sqrt(dr * dr + di * di);
            acc.GaussianCount++;
        }

        // expSmooth — mean of e^{−|z_n|} (Kerry Mitchell).
        if (F_exp)
        {
            double a = Math.Sqrt(zr * zr + zi * zi);
            acc.ExpSum += Math.Exp(-a);
            acc.ExpCount++;
        }

        // curvature — mean |Δarg| between successive orbit segments.
        if (F_curvature)
        {
            if (iter == 1) { acc.PrevZr = zr; acc.PrevZi = zi; }
            else
            {
                double segR = zr - acc.PrevZr, segI = zi - acc.PrevZi;
                if (iter == 2) { acc.PrevSegR = segR; acc.PrevSegI = segI; }
                else
                {
                    double cross = acc.PrevSegR * segI - acc.PrevSegI * segR;
                    double dot = acc.PrevSegR * segR + acc.PrevSegI * segI;
                    if (cross != 0.0 || dot != 0.0)
                    {
                        acc.CurvatureSum += Math.Abs(Math.Atan2(cross, dot));
                        acc.CurvatureCount++;
                    }
                    acc.PrevSegR = segR; acc.PrevSegI = segI;
                }
                acc.PrevZr = zr; acc.PrevZi = zi;
            }
        }
    }

    public int MapWithOrbit(float smooth, float distance, int iterations,
                            float nx, float ny, in OrbitAccumulator acc)
    {
        // ── Input adapter: escape-final inputs + accumulated orbit means. ─────
        double in_smooth  = smooth;
        double in_dist    = distance;
        double in_iter    = (double)iterations;
        double in_maxIter = (double)MaxIterations;
        double in_t       = MaxIterations > 0 ? smooth / (double)MaxIterations : 0.0;
        double in_nx      = nx;
        double in_ny      = ny;
        double in_zr      = 0.0;
        double in_zi      = 0.0;
        double in_dzr     = 0.0;
        double in_dzi     = 0.0;
        double in_arg     = 0.0;
        double in_mag     = 0.0;
        double in_isInSet = iterations >= MaxIterations ? 1.0 : 0.0;
        double in_pxScale = _pixelScale;

        // Orbit means (raw — the DSL scales them). Unreferenced ones stay 0.
        double in_trapMin       = acc.TrapMin  == float.MaxValue ? 0.0 : acc.TrapMin;
        double in_trapCross     = acc.TrapMin2 == float.MaxValue ? 0.0 : acc.TrapMin2;
        double in_trapRing      = acc.TrapMin3 == float.MaxValue ? 0.0 : acc.TrapMin3;
        double in_trapHyperbola = acc.TrapMin4 == float.MaxValue ? 0.0 : acc.TrapMin4;
        double in_trapHexagon   = acc.TrapMin5 == float.MaxValue ? 0.0 : acc.TrapMin5;
        double in_stripeAvg = acc.StripeCount    > 0 ? acc.StripeSum    / acc.StripeCount    : 0.0;
        double in_tiaAvg    = acc.TiaCount       > 0 ? acc.TiaSum       / acc.TiaCount       : 0.0;
        double in_curvature = acc.CurvatureCount > 0 ? acc.CurvatureSum / acc.CurvatureCount : 0.0;
        double in_lyapunov  = acc.LyapunovCount  > 0 ? acc.LyapunovSum  / acc.LyapunovCount  : 0.0;
        double in_gaussian  = acc.GaussianCount  > 0 ? acc.GaussianSum  / acc.GaussianCount  : 0.0;
        double in_expSmooth = acc.ExpCount       > 0 ? acc.ExpSum       / acc.ExpCount       : 0.0;

{{BODY}}
    }

    // ── IColorMap escape-final overloads. ────────────────────────────────────
    // No orbit was sampled on this path, so the orbit inputs bind to 0. Themes
    // are normally rendered via MapWithOrbit; these keep stand-alone/recolour
    // paths (which lack an accumulator) valid.

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public int Map(float smooth, float distance, int iterations)
        => Map(smooth, distance, iterations, 0f, 0f, 0f, 0f, 0f, 0f);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public int Map(float smooth, float distance, int iterations, float nx, float ny)
        => Map(smooth, distance, iterations, nx, ny, 0f, 0f, 0f, 0f);

    public int Map(float smooth, float distance, int iterations,
                   float nx, float ny,
                   float finalZr, float finalZi, float dzdcR, float dzdcI)
    {
        double in_smooth  = smooth;
        double in_dist    = distance;
        double in_iter    = (double)iterations;
        double in_maxIter = (double)MaxIterations;
        double in_t       = MaxIterations > 0 ? smooth / (double)MaxIterations : 0.0;
        double in_nx      = nx;
        double in_ny      = ny;
        double in_zr      = finalZr;
        double in_zi      = finalZi;
        double in_dzr     = dzdcR;
        double in_dzi     = dzdcI;
        double in_arg     = System.Math.Atan2((double)finalZi, (double)finalZr);
        double in_mag     = System.Math.Sqrt((double)finalZr * finalZr + (double)finalZi * finalZi);
        double in_isInSet = iterations >= MaxIterations ? 1.0 : 0.0;
        double in_pxScale = _pixelScale;

        // No orbit accumulator on the escape-final path — orbit inputs are 0.
        double in_trapMin       = 0.0;
        double in_trapCross     = 0.0;
        double in_trapRing      = 0.0;
        double in_trapHyperbola = 0.0;
        double in_trapHexagon   = 0.0;
        double in_stripeAvg = 0.0;
        double in_tiaAvg    = 0.0;
        double in_curvature = 0.0;
        double in_lyapunov  = 0.0;
        double in_gaussian  = 0.0;
        double in_expSmooth = 0.0;

{{BODY}}
    }

    // ── Runtime helpers (Cg3 + scalar utilities + ARGB packer) ───────────────

    private static int PackArgb(Cg3 c)
    {
        int r = (int)(System.Math.Clamp(c.R, 0.0, 1.0) * 255.0 + 0.5);
        int g = (int)(System.Math.Clamp(c.G, 0.0, 1.0) * 255.0 + 0.5);
        int b = (int)(System.Math.Clamp(c.B, 0.0, 1.0) * 255.0 + 0.5);
        return unchecked((int)0xFF000000) | (r << 16) | (g << 8) | b;
    }

    internal readonly record struct Cg3(double R, double G, double B)
    {
        // ── Elementwise + - * / on Cg3↔Cg3 (Cg3↔Scalar variants follow). ──
        public static Cg3 Add(Cg3 a, Cg3 b) => new(a.R + b.R, a.G + b.G, a.B + b.B);
        public static Cg3 AddVS(Cg3 a, double s) => new(a.R + s, a.G + s, a.B + s);
        public static Cg3 AddSV(double s, Cg3 a) => new(s + a.R, s + a.G, s + a.B);
        public static Cg3 Sub(Cg3 a, Cg3 b) => new(a.R - b.R, a.G - b.G, a.B - b.B);
        public static Cg3 SubVS(Cg3 a, double s) => new(a.R - s, a.G - s, a.B - s);
        public static Cg3 SubSV(double s, Cg3 a) => new(s - a.R, s - a.G, s - a.B);
        public static Cg3 Mul(Cg3 a, Cg3 b) => new(a.R * b.R, a.G * b.G, a.B * b.B);
        public static Cg3 MulVS(Cg3 a, double s) => new(a.R * s, a.G * s, a.B * s);
        public static Cg3 MulSV(double s, Cg3 a) => new(s * a.R, s * a.G, s * a.B);
        public static Cg3 Div(Cg3 a, Cg3 b) => new(a.R / b.R, a.G / b.G, a.B / b.B);
        public static Cg3 DivVS(Cg3 a, double s) => new(a.R / s, a.G / s, a.B / s);
        public static Cg3 DivSV(double s, Cg3 a) => new(s / a.R, s / a.G, s / a.B);
        public static Cg3 Neg(Cg3 a) => new(-a.R, -a.G, -a.B);

        public static Cg3 Mod(Cg3 a, Cg3 b)
            => new(CgScalar.Mod(a.R, b.R), CgScalar.Mod(a.G, b.G), CgScalar.Mod(a.B, b.B));
        public static Cg3 ModVS(Cg3 a, double s)
            => new(CgScalar.Mod(a.R, s), CgScalar.Mod(a.G, s), CgScalar.Mod(a.B, s));
        public static Cg3 ModSV(double s, Cg3 a)
            => new(CgScalar.Mod(s, a.R), CgScalar.Mod(s, a.G), CgScalar.Mod(s, a.B));

        public static Cg3 Pow(Cg3 a, Cg3 b)
            => new(System.Math.Pow(a.R, b.R), System.Math.Pow(a.G, b.G), System.Math.Pow(a.B, b.B));
        public static Cg3 PowVS(Cg3 a, double s)
            => new(System.Math.Pow(a.R, s), System.Math.Pow(a.G, s), System.Math.Pow(a.B, s));
        public static Cg3 PowSV(double s, Cg3 a)
            => new(System.Math.Pow(s, a.R), System.Math.Pow(s, a.G), System.Math.Pow(s, a.B));

        public static Cg3 Mix(Cg3 a, Cg3 b, double t)
            => new(a.R + (b.R - a.R) * t,
                   a.G + (b.G - a.G) * t,
                   a.B + (b.B - a.B) * t);

        public static Cg3 FromHsv(double h, double s, double v)
        {
            // Cyclic hue in [0,1). HSV→RGB with the standard 6-segment lookup.
            h = h - System.Math.Floor(h);
            s = System.Math.Clamp(s, 0.0, 1.0);
            v = System.Math.Clamp(v, 0.0, 1.0);
            double hh = h * 6.0;
            int i = (int)System.Math.Floor(hh);
            double f = hh - i;
            double p = v * (1.0 - s);
            double q = v * (1.0 - f * s);
            double tt = v * (1.0 - (1.0 - f) * s);
            return (i % 6) switch
            {
                0 => new Cg3(v, tt, p),
                1 => new Cg3(q, v, p),
                2 => new Cg3(p, v, tt),
                3 => new Cg3(p, q, v),
                4 => new Cg3(tt, p, v),
                _ => new Cg3(v, p, q),
            };
        }

        public static Cg3 FromHsl(double h, double s, double l)
        {
            h = h - System.Math.Floor(h);
            s = System.Math.Clamp(s, 0.0, 1.0);
            l = System.Math.Clamp(l, 0.0, 1.0);
            double c = (1.0 - System.Math.Abs(2.0 * l - 1.0)) * s;
            double hh = h * 6.0;
            double x = c * (1.0 - System.Math.Abs((hh % 2.0) - 1.0));
            double m = l - c * 0.5;
            double r1, g1, b1;
            int seg = (int)System.Math.Floor(hh);
            switch (seg % 6)
            {
                case 0: r1 = c; g1 = x; b1 = 0; break;
                case 1: r1 = x; g1 = c; b1 = 0; break;
                case 2: r1 = 0; g1 = c; b1 = x; break;
                case 3: r1 = 0; g1 = x; b1 = c; break;
                case 4: r1 = x; g1 = 0; b1 = c; break;
                default:r1 = c; g1 = 0; b1 = x; break;
            }
            return new Cg3(r1 + m, g1 + m, b1 + m);
        }

        /// <summary>Cyclic linear palette: stops are evenly spaced on [0,1)
        /// with t wrapping (fract). With N stops the segment for t lands in
        /// [k/N, (k+1)/N) and lerps between stops[k] and stops[(k+1)%N].</summary>
        public static Cg3 Palette(double t, params Cg3[] stops)
        {
            int n = stops.Length;
            if (n == 0) return new Cg3(0, 0, 0);
            if (n == 1) return stops[0];
            double frac = t - System.Math.Floor(t);
            double pos = frac * n;
            int k = (int)System.Math.Floor(pos) % n;
            int k2 = (k + 1) % n;
            double f = pos - System.Math.Floor(pos);
            return Mix(stops[k], stops[k2], f);
        }

        /// <summary>Inigo Quilez cosine palette: a + b·cos(2π·(c·t + d)).
        /// a,b,c,d are per-channel coefficient vectors. Output is unclamped
        /// (the ARGB packer clamps to [0,1]).</summary>
        public static Cg3 Cosine(double t, Cg3 a, Cg3 b, Cg3 c, Cg3 d)
        {
            const double tau = 6.283185307179586;
            return new Cg3(
                a.R + b.R * System.Math.Cos(tau * (c.R * t + d.R)),
                a.G + b.G * System.Math.Cos(tau * (c.G * t + d.G)),
                a.B + b.B * System.Math.Cos(tau * (c.B * t + d.B)));
        }

        // ── OkLab (Björn Ottosson) — perceptually uniform colour (F9). ──────
        private static double SrgbToLinear(double c)
        {
            c = System.Math.Clamp(c, 0.0, 1.0);
            return c <= 0.04045 ? c / 12.92 : System.Math.Pow((c + 0.055) / 1.055, 2.4);
        }

        private static double LinearToSrgb(double c)
        {
            c = System.Math.Clamp(c, 0.0, 1.0);
            return c <= 0.0031308 ? c * 12.92 : 1.055 * System.Math.Pow(c, 1.0 / 2.4) - 0.055;
        }

        public static Cg3 FromOkLab(double L, double a, double b)
        {
            double l_ = L + 0.3963377774 * a + 0.2158037573 * b;
            double m_ = L - 0.1055613458 * a - 0.0638541728 * b;
            double s_ = L - 0.0894841775 * a - 1.2914855480 * b;
            double l = l_ * l_ * l_, m = m_ * m_ * m_, s = s_ * s_ * s_;
            double r =  4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s;
            double g = -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s;
            double bb = -0.0041960863 * l - 0.7034186147 * m + 1.7076147010 * s;
            return new Cg3(LinearToSrgb(r), LinearToSrgb(g), LinearToSrgb(bb));
        }

        public static Cg3 FromOkLch(double L, double c, double h)
            => FromOkLab(L, c * System.Math.Cos(h), c * System.Math.Sin(h));

        private static Cg3 ToOkLab(Cg3 c)
        {
            double r = SrgbToLinear(c.R), g = SrgbToLinear(c.G), b = SrgbToLinear(c.B);
            double l = 0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b;
            double m = 0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b;
            double s = 0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b;
            double l_ = System.Math.Cbrt(l), m_ = System.Math.Cbrt(m), s_ = System.Math.Cbrt(s);
            return new Cg3(
                0.2104542553 * l_ + 0.7936177850 * m_ - 0.0040720468 * s_,
                1.9779984951 * l_ - 2.4285922050 * m_ + 0.4505937099 * s_,
                0.0259040371 * l_ + 0.7827717662 * m_ - 0.8086757660 * s_);
        }

        public static Cg3 MixOkLab(Cg3 a, Cg3 b, double t)
        {
            Cg3 la = ToOkLab(a), lb = ToOkLab(b);
            return FromOkLab(la.R + (lb.R - la.R) * t,
                             la.G + (lb.G - la.G) * t,
                             la.B + (lb.B - la.B) * t);
        }

        public static Cg3 Brightness(Cg3 a, double s) => new(a.R + s, a.G + s, a.B + s);

        public static Cg3 Contrast(Cg3 a, double s)
        {
            double f = 1.0 + s;
            return new(0.5 + (a.R - 0.5) * f,
                       0.5 + (a.G - 0.5) * f,
                       0.5 + (a.B - 0.5) * f);
        }

        public static Cg3 Gamma(Cg3 a, double g)
        {
            double e = g <= 0.0 ? 1.0 : 1.0 / g;
            return new(System.Math.Pow(System.Math.Max(0, a.R), e),
                       System.Math.Pow(System.Math.Max(0, a.G), e),
                       System.Math.Pow(System.Math.Max(0, a.B), e));
        }
    }

    internal static class CgScalar
    {
        public static double Fract(double x) => x - System.Math.Floor(x);

        public static double Hypot(double x, double y) => System.Math.Sqrt(x * x + y * y);

        public static double Mod(double x, double y)
        {
            if (y == 0.0) return 0.0;
            return x - y * System.Math.Floor(x / y);
        }

        public static double Smoothstep(double edge0, double edge1, double x)
        {
            double t = (x - edge0) / (edge1 - edge0);
            if (t < 0.0) t = 0.0; else if (t > 1.0) t = 1.0;
            return t * t * (3.0 - 2.0 * t);
        }

        public static double Hash(double x)
        {
            return Fract(System.Math.Sin(x * 12.9898) * 43758.5453);
        }

        public static double Hash2(double x, double y)
        {
            return Fract(System.Math.Sin(x * 12.9898 + y * 78.233) * 43758.5453);
        }
    }
}
